# Generated by Django 6.0.4 on 2026-05-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name='全称')),
                ('province', models.CharField(blank=True, default='', max_length=50, verbose_name='所属省份')),
                ('lng', models.FloatField(verbose_name='经度')),
                ('lat', models.FloatField(verbose_name='纬度')),
                ('city_type', models.CharField(default='地级市', max_length=20, verbose_name='类型')),
                ('pinyin', models.CharField(blank=True, default='', max_length=100, verbose_name='拼音')),
            ],
            options={
                'verbose_name': '城市坐标',
                'db_table': 'toolkit_city_coordinate',
                'ordering': ['province', 'name'],
                'indexes': [models.Index(fields=['name'], name='toolkit_cit_name_199977_idx'), models.Index(fields=['province'], name='toolkit_cit_provinc_504fe9_idx')],
            },
        ),
    ]
