# Generated by Django 6.0.4 on 2026-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0002_citycoordinate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRoutePreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('name', models.CharField(max_length=200, verbose_name='路线名称')),
                ('origin', models.CharField(max_length=100, verbose_name='出发地')),
                ('destinations', models.JSONField(default=list, verbose_name='目的地列表')),
                ('description', models.TextField(blank=True, default='', verbose_name='路线描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '旅行路线预设',
                'db_table': 'toolkit_travel_route_preset',
                'ordering': ['-created_at'],
            },
        ),
    ]
