# Generated by Django 6.0.4 on 2026-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_travelroutepreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('environment_name', models.CharField(max_length=200, verbose_name='环境名称')),
                ('audit_date', models.DateField(verbose_name='校准日期')),
                ('allow_learning', models.IntegerField(default=0, verbose_name='允许说不知道')),
                ('system_valued', models.IntegerField(default=0, verbose_name='系统能力被珍视')),
                ('signal_over_noise', models.IntegerField(default=0, verbose_name='信号大于噪音')),
                ('body_heard', models.IntegerField(default=0, verbose_name='身体能被听见')),
                ('people_share', models.IntegerField(default=0, verbose_name='高手愿意分享')),
                ('output_echoes', models.IntegerField(default=0, verbose_name='输出有回路')),
                ('total_score', models.IntegerField(default=0, verbose_name='总分')),
                ('verdict', models.CharField(max_length=20, verbose_name='判定')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '环境校准记录',
                'db_table': 'toolkit_environment_audit',
                'ordering': ['-audit_date'],
            },
        ),
    ]
