# Generated by Django 6.0.4 on 2026-06-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_environment_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEnergyAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('audit_date', models.DateField(verbose_name='审计日期')),
                ('task_clarity', models.IntegerField(default=0, help_text='-5=每天等人给活, +5=知道自己要做什么', verbose_name='任务清晰度')),
                ('skill_match', models.IntegerField(default=0, help_text='-5=总被说半吊子, +5=在能力范围内', verbose_name='技能匹配度')),
                ('autonomy', models.IntegerField(default=0, help_text='-5=每个细节要请示, +5=能自己决定', verbose_name='自主决策权')),
                ('achievement', models.IntegerField(default=0, help_text='-5=做完也没感觉, +5=完成一件事的感觉', verbose_name='成就感')),
                ('learning', models.IntegerField(default=0, help_text='-5=重复劳动, +5=能学到新东西', verbose_name='学习机会')),
                ('workload', models.IntegerField(default=0, help_text='-5=天天加班, +5=工作时间内完成', verbose_name='工作量合理性')),
                ('visibility', models.IntegerField(default=0, help_text='-5=不知道有什么用, +5=能看到产出', verbose_name='结果可见性')),
                ('communication', models.IntegerField(default=0, help_text='-5=反复解释被误解, +5=一句话说清楚', verbose_name='沟通效率')),
                ('transparency', models.IntegerField(default=0, help_text='-5=突然被告知, +5=变更有通知', verbose_name='信息透明度')),
                ('respect', models.IntegerField(default=0, help_text='-5=被敷衍啧唉, +5=意见被认真对待', verbose_name='被尊重程度')),
                ('feedback_quality', models.IntegerField(default=0, help_text='-5=你是不是不懂, +5=指向具体问题', verbose_name='反馈质量')),
                ('process_smooth', models.IntegerField(default=0, help_text='-5=处处受阻, +5=需求不被卡', verbose_name='流程顺畅度')),
                ('commute', models.IntegerField(default=0, help_text='-5=消耗巨大, +5=轻松到达', verbose_name='通勤体验')),
                ('physical_env', models.IntegerField(default=0, help_text='-5=不舒适, +5=舒适', verbose_name='物理环境')),
                ('colleague_relation', models.IntegerField(default=0, help_text='-5=需要防备, +5=相处融洽', verbose_name='同事关系')),
                ('skill_growth', models.IntegerField(default=0, help_text='-5=原地踏步, +5=在提升', verbose_name='技能成长')),
                ('vision_expand', models.IntegerField(default=0, help_text='-5=信息茧房, +5=接触新思维', verbose_name='视野拓展')),
                ('resume_value', models.IntegerField(default=0, help_text='-5=纯粹耗时间, +5=对未来有帮助', verbose_name='履历增值')),
                ('income_satisfy', models.IntegerField(default=0, help_text='-5=觉得不值, +5=匹配付出', verbose_name='收入满意度')),
                ('direction', models.IntegerField(default=0, help_text='-5=迷茫, +5=知道往哪走', verbose_name='方向感')),
                ('morning_feeling', models.IntegerField(default=3, help_text='1=期待, 5=恐惧', verbose_name='早起感受')),
                ('sunday_anxiety', models.IntegerField(default=3, help_text='1=完全放松, 5=极度焦虑', verbose_name='周日焦虑')),
                ('after_work_state', models.IntegerField(default=3, help_text='1=还有精力, 5=瘫倒不想动', verbose_name='下班后状态')),
                ('sleep_quality', models.IntegerField(default=3, help_text='1=倒头就睡, 5=失眠早醒', verbose_name='睡眠质量')),
                ('body_signals', models.CharField(blank=True, default='', max_length=200, verbose_name='身体信号')),
                ('emotion_stability', models.IntegerField(default=3, help_text='1=情绪稳定, 5=经常失控', verbose_name='情绪波动')),
                ('total_score', models.IntegerField(default=0, help_text='范围-130~+130', verbose_name='总分')),
                ('work_score', models.IntegerField(default=0, verbose_name='工作内容得分')),
                ('env_score', models.IntegerField(default=0, verbose_name='环境与人得分')),
                ('growth_score', models.IntegerField(default=0, verbose_name='成长与未来得分')),
                ('body_score', models.IntegerField(default=0, verbose_name='身体与情绪得分')),
                ('decision', models.CharField(default='待观察', max_length=20, verbose_name='判定')),
                ('advice', models.TextField(blank=True, default='', verbose_name='建议')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='下次审计日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '职业能量审计记录',
                'db_table': 'toolkit_career_energy_audit',
                'ordering': ['-audit_date'],
            },
        ),
    ]
