# Generated by Django 6.0.4 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_career_energy_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(blank=True, default='', max_length=200, verbose_name='作者/出处')),
                ('language', models.CharField(choices=[('中文', '🇨🇳 中文'), ('英语', '🇬🇧 英语'), ('日语', '🇯🇵 日语'), ('德语', '🇩🇪 德语'), ('法语', '🇫🇷 法语'), ('韩语', '🇰🇷 韩语'), ('其他', '🌐 其他')], default='中文', max_length=20, verbose_name='语言')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='分类')),
                ('is_paragraph', models.BooleanField(default=False, verbose_name='是否段落')),
                ('short_title', models.CharField(blank=True, default='', max_length=100, verbose_name='缩减标题')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='来源')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('review_count', models.IntegerField(default=0, verbose_name='回顾次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '金句',
                'db_table': 'toolkit_quote',
                'ordering': ['-created_at'],
            },
        ),
    ]
