# Generated by Django 6.0.4 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0006_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='标签'),
        ),
    ]
