# Generated by Django 6.0.4 on 2026-06-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0007_quote_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSelfCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('check_date', models.DateField(verbose_name='检查日期')),
                ('headache', models.CharField(default='无', max_length=20, verbose_name='头痛/偏头痛')),
                ('dizzy', models.CharField(default='无', max_length=20, verbose_name='头晕/眩晕')),
                ('hairloss', models.CharField(default='正常', max_length=20, verbose_name='脱发')),
                ('memory', models.CharField(default='无变化', max_length=20, verbose_name='记忆力变化')),
                ('vision', models.CharField(default='无', max_length=20, verbose_name='视力模糊/眼干')),
                ('ear', models.CharField(default='无', max_length=20, verbose_name='耳鸣/听力')),
                ('ulcer', models.CharField(default='无', max_length=20, verbose_name='口腔溃疡')),
                ('gum', models.CharField(default='无', max_length=20, verbose_name='牙龈出血')),
                ('allergy', models.CharField(default='无', max_length=20, verbose_name='鼻塞/过敏')),
                ('spots', models.CharField(default='无', max_length=20, verbose_name='新发痣/斑')),
                ('spots_location', models.CharField(blank=True, default='', max_length=100, verbose_name='痣/斑部位')),
                ('rash', models.CharField(default='无', max_length=20, verbose_name='皮疹/瘙痒')),
                ('wound_healing', models.CharField(default='正常', max_length=20, verbose_name='伤口愈合速度')),
                ('joint', models.CharField(default='无', max_length=20, verbose_name='关节疼痛/僵硬')),
                ('numbness', models.CharField(default='无', max_length=20, verbose_name='手脚发麻')),
                ('muscle', models.CharField(default='无', max_length=20, verbose_name='肌肉酸痛')),
                ('finger_flex', models.CharField(default='正常', max_length=20, verbose_name='手指灵活性')),
                ('appetite', models.CharField(default='正常', max_length=20, verbose_name='食欲')),
                ('bloating', models.CharField(default='无', max_length=20, verbose_name='腹胀/打嗝')),
                ('abdominal_pain', models.CharField(default='无', max_length=20, verbose_name='腹痛')),
                ('reflux', models.CharField(default='无', max_length=20, verbose_name='胃酸反流')),
                ('stool_count', models.IntegerField(blank=True, null=True, verbose_name='大便次数')),
                ('stool_type', models.CharField(default='正常', max_length=20, verbose_name='大便性状')),
                ('urination_pain', models.CharField(default='无', max_length=20, verbose_name='尿频/尿急/尿痛')),
                ('nocturia', models.IntegerField(blank=True, null=True, verbose_name='夜尿次数')),
                ('sleep_latency', models.IntegerField(blank=True, null=True, verbose_name='入睡时间(分钟)')),
                ('awakenings', models.IntegerField(blank=True, null=True, verbose_name='夜间醒来次数')),
                ('morning_energy', models.CharField(default='恢复感好', max_length=20, verbose_name='晨起精力')),
                ('snoring', models.CharField(default='无', max_length=20, verbose_name='打鼾')),
                ('fatigue', models.CharField(default='无', max_length=20, verbose_name='疲劳感')),
                ('mood', models.CharField(default='偶尔', max_length=20, verbose_name='情绪低落/焦虑')),
                ('afternoon_fatigue', models.CharField(default='偶尔', max_length=20, verbose_name='午后犯困')),
                ('interest_change', models.CharField(default='正常', max_length=20, verbose_name='兴趣变化')),
                ('health_score', models.IntegerField(default=0, verbose_name='健康分')),
                ('last_score', models.IntegerField(blank=True, null=True, verbose_name='上次分数')),
                ('score_change', models.IntegerField(blank=True, null=True, verbose_name='分数变化')),
                ('alert_items', models.TextField(blank=True, default='', verbose_name='异常项汇总')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '身体健康自查',
                'db_table': 'toolkit_health_self_check',
                'ordering': ['-check_date'],
            },
        ),
    ]
