# Generated by Django 6.0.4 on 2026-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0008_healthselfcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('title', models.CharField(max_length=200, verbose_name='决策标题')),
                ('decision_date', models.DateField(verbose_name='决策日期')),
                ('category', models.CharField(choices=[('职业', '职业'), ('关系', '关系'), ('财务', '财务'), ('健康', '健康'), ('居住', '居住'), ('学习', '学习'), ('其他', '其他')], default='其他', max_length=20, verbose_name='分类')),
                ('background', models.TextField(verbose_name='背景/情境')),
                ('options', models.JSONField(default=list, help_text='[{name, pros, cons}]', verbose_name='选项列表')),
                ('chosen', models.CharField(max_length=200, verbose_name='最终选择')),
                ('reason', models.TextField(verbose_name='选择理由')),
                ('expected_outcome', models.TextField(verbose_name='预期结果')),
                ('fear_factor', models.IntegerField(default=5, help_text='1-10', verbose_name='恐惧指数')),
                ('actual_outcome', models.TextField(blank=True, default='', verbose_name='实际结果（半年后回顾）')),
                ('was_right', models.BooleanField(blank=True, null=True, verbose_name='决策是否正确')),
                ('learned', models.TextField(blank=True, default='', verbose_name='学到的经验')),
                ('bias_found', models.CharField(blank=True, default='', max_length=100, verbose_name='发现的偏误')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='回顾日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '决策日志',
                'db_table': 'toolkit_decision_log',
                'ordering': ['-decision_date'],
            },
        ),
    ]
