# Generated by Django 6.0.4 on 2026-06-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0009_decision_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSpendingCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('liquid_assets', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='可支配流动资产(元)')),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='年稳定收入(元)')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='固定债务(元)')),
                ('work_years', models.IntegerField(default=20, verbose_name='预计工作年限')),
                ('free_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计算结果(元/次)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自由支配额度计算',
                'db_table': 'toolkit_free_spending',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': '摘录'},
        ),
    ]
