# Generated by Django 6.0.4 on 2026-06-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0010_free_spending_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('review_type', models.CharField(choices=[('daily', '每日复盘'), ('weekly', '周复盘'), ('monthly', '月复盘'), ('quarterly', '季度复盘'), ('life', '人生编舟')], max_length=20, verbose_name='复盘类型')),
                ('review_date', models.DateField(verbose_name='复盘日期')),
                ('daily_status', models.CharField(blank=True, default='', max_length=50, verbose_name='状态')),
                ('daily_people', models.TextField(blank=True, default='', verbose_name='那些人那些事')),
                ('johari_window', models.JSONField(blank=True, default=dict, verbose_name='约哈里窗')),
                ('emotions', models.JSONField(blank=True, default=dict, verbose_name='情绪清单')),
                ('completed', models.TextField(blank=True, default='', verbose_name='本周/月完成')),
                ('plan_next', models.TextField(blank=True, default='', verbose_name='下周/月计划')),
                ('reflection', models.TextField(blank=True, default='', verbose_name='反思总结')),
                ('grai', models.JSONField(blank=True, default=dict, verbose_name='GRAI复盘')),
                ('orid', models.JSONField(blank=True, default=dict, verbose_name='ORID复盘')),
                ('nourishing', models.TextField(blank=True, default='', verbose_name='滋养小事')),
                ('draining', models.TextField(blank=True, default='', verbose_name='消耗黑洞')),
                ('fears', models.TextField(blank=True, default='', verbose_name='害怕的事')),
                ('worries', models.TextField(blank=True, default='', verbose_name='烦恼的事')),
                ('envy_target', models.TextField(blank=True, default='', verbose_name='羡慕的对象')),
                ('regret_at_80', models.TextField(blank=True, default='', verbose_name='80岁遗憾')),
                ('life_paths', models.TextField(blank=True, default='', verbose_name='5年路径推演')),
                ('life_line', models.TextField(blank=True, default='', verbose_name='生命线回顾')),
                ('personal_goals', models.TextField(blank=True, default='', verbose_name='个人目标')),
                ('time_plan', models.TextField(blank=True, default='', verbose_name='四象限规划')),
                ('deep_reflection', models.TextField(blank=True, default='', verbose_name='深度复盘')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '复盘记录',
                'db_table': 'toolkit_review_record',
                'ordering': ['-review_date', '-created_at'],
                'indexes': [models.Index(fields=['review_type'], name='toolkit_rev_review__181217_idx'), models.Index(fields=['review_date'], name='toolkit_rev_review__a879c7_idx')],
            },
        ),
    ]
