# Generated by Django 6.0.4 on 2026-06-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0011_review_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyWageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='记录名称')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月薪(元)')),
                ('rest_type', models.CharField(choices=[('双休', '双休'), ('单休', '单休'), ('大小周', '大小周'), ('不休', '不休')], default='双休', max_length=20, verbose_name='休息类型')),
                ('work_start', models.CharField(default='09:00', max_length=5, verbose_name='上班时间')),
                ('work_end', models.CharField(default='18:00', max_length=5, verbose_name='下班时间')),
                ('lunch_break', models.IntegerField(default=60, verbose_name='午休时长(分钟)')),
                ('commute_minutes', models.IntegerField(default=0, verbose_name='单程通勤(分钟)')),
                ('work_days_per_month', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='月工作天数')),
                ('work_hours_per_day', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='日工作小时')),
                ('total_hours_per_month', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='月总投入小时')),
                ('hourly_wage', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='时薪(元/时)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'toolkit_hourly_wage',
                'ordering': ['-created_at'],
            },
        ),
    ]
