# Generated by Django 6.0.4 on 2026-06-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0012_hourlywagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlywagerecord',
            name='calc_mode',
            field=models.CharField(choices=[('formal', '🏢 正式职业'), ('freelance', '🧑\u200d💻 自由职业')], default='formal', max_length=20, verbose_name='计算模式'),
        ),
        migrations.AddField(
            model_name='hourlywagerecord',
            name='freelance_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='月工作天数'),
        ),
        migrations.AddField(
            model_name='hourlywagerecord',
            name='freelance_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='日均工作时长'),
        ),
        migrations.AddField(
            model_name='hourlywagerecord',
            name='freelance_time_mode',
            field=models.CharField(choices=[('fixed', '固定时长'), ('flexible', '弹性工时')], default='fixed', max_length=10, verbose_name='工时模式'),
        ),
        migrations.AddField(
            model_name='hourlywagerecord',
            name='freelance_weeks',
            field=models.IntegerField(default=4, verbose_name='每月周数'),
        ),
        migrations.AddField(
            model_name='hourlywagerecord',
            name='weekly_hours',
            field=models.JSONField(default=list, verbose_name='每周各天工作时长'),
        ),
    ]
