# Generated by Django 6.0.4 on 2026-07-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0013_hourlywagerecord_calc_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('train_type', models.CharField(choices=[('granularity', '词汇颗粒度'), ('describe', '场景描述'), ('material', '语言素材'), ('revision', '逼近修订')], max_length=20, verbose_name='训练类型')),
                ('train_date', models.DateField(verbose_name='训练日期')),
                ('rough_word', models.CharField(blank=True, default='', max_length=50, verbose_name='粗糙词汇')),
                ('refined_words', models.TextField(blank=True, default='', verbose_name='拆分后的词汇')),
                ('summary', models.CharField(blank=True, default='', max_length=200, verbose_name='总结性描述')),
                ('scene', models.TextField(blank=True, default='', verbose_name='场景还原')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='来源')),
                ('quote_text', models.TextField(blank=True, default='', verbose_name='原句')),
                ('why_good', models.TextField(blank=True, default='', verbose_name='为什么觉得好')),
                ('first_draft', models.TextField(blank=True, default='', verbose_name='第一版')),
                ('revisions', models.JSONField(blank=True, default=list, verbose_name='修订过程')),
                ('final_version', models.TextField(blank=True, default='', verbose_name='最终版')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '语言训练记录',
                'db_table': 'toolkit_language_training',
                'ordering': ['-train_date'],
                'indexes': [models.Index(fields=['train_type'], name='toolkit_lan_train_t_1d0c75_idx'), models.Index(fields=['train_date'], name='toolkit_lan_train_d_dc60e2_idx')],
            },
        ),
    ]
