# Generated by Django 6.0.4 on 2026-08-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0014_languagetraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('name', models.CharField(max_length=200, verbose_name='记录名称')),
                ('items', models.JSONField(default=list, help_text='[{name, amount, icon}]', verbose_name='开销项目列表')),
                ('total_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月固定开销')),
                ('total_daily', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='日均固定开销')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '固定开销计算',
                'db_table': 'toolkit_fixed_expense',
                'ordering': ['-created_at'],
            },
        ),
    ]
