# Generated by Django 6.0.4 on 2026-08-05 02:32

from django.db import migrations, models
from django.db.models import F


def backfill_total_yearly(apps, schema_editor):
    FixedExpense = apps.get_model('toolkit', 'FixedExpense')
    # 旧数据按每月口径换算：年开销 = 日均 × 365
    FixedExpense.objects.update(total_yearly=F('total_daily') * 365)


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_squashed_0018'),
    ]

    operations = [
        # 注：AddField total_yearly / AlterField items 已并入 0001_squashed_0018（净效果），此处仅保留数据回填
        migrations.RunPython(backfill_total_yearly, migrations.RunPython.noop),
    ]
