# Generated by Django 6.0.4 on 2026-08-05 02:32

from django.db import migrations, models
from django.db.models import F


def backfill_total_yearly(apps, schema_editor):
    FixedExpense = apps.get_model('toolkit', 'FixedExpense')
    # 旧数据按每月口径换算：年开销 = 日均 × 365
    FixedExpense.objects.update(total_yearly=F('total_daily') * 365)


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0015_fixedexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='total_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='年固定开销'),
        ),
        migrations.AlterField(
            model_name='fixedexpense',
            name='items',
            field=models.JSONField(default=list, help_text='[{name, amount, period, icon}]，period 支持 daily/monthly/yearly', verbose_name='开销项目列表'),
        ),
        migrations.RunPython(backfill_total_yearly, migrations.RunPython.noop),
    ]
