# Generated by Django 6.0.4 on 2026-08-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0016_fixedexpense_total_yearly_alter_fixedexpense_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlywagerecord',
            name='extra_incomes',
            field=models.JSONField(default=list, help_text='[{"name":"公众号","amount":300,"period":"monthly"}]', verbose_name='额外收入来源'),
        ),
    ]
