# Generated by Django 6.0.4 on 2026-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0017_hourlywagerecord_extra_incomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('meter_reading', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='电表读数(度)')),
                ('interval_usage', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='间隔用电量(度)')),
                ('interval_days', models.IntegerField(blank=True, null=True, verbose_name='间隔天数')),
                ('daily_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='日均用电量(度/天)')),
                ('month_usage', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='本月累计用电量(度)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用电记录',
                'db_table': 'toolkit_electricity_record',
                'ordering': ['-record_date'],
            },
        ),
    ]
