# Generated by Django 6.0.4 on 2026-08-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('alias', models.CharField(blank=True, max_length=100, verbose_name='别名')),
                ('sample_type', models.CharField(choices=[('acquaintance', '熟人'), ('online', '网友'), ('historical', '历史人物'), ('celebrity', '知名人士'), ('fictional', '虚构人物')], default='historical', max_length=20, verbose_name='类型')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='一句话简介')),
                ('obsidian_path', models.CharField(blank=True, help_text='相对于Obsidian仓库根目录，如：LifeSamples/曾国藩.md', max_length=500, verbose_name='Obsidian文件路径')),
                ('my_note', models.TextField(blank=True, verbose_name='我的笔记')),
                ('related_goals', models.JSONField(blank=True, default=list, verbose_name='关联目标')),
                ('related_diary', models.JSONField(blank=True, default=list, verbose_name='关联日记')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'life_sample',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObsidianConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用集成')),
                ('vault_path', models.CharField(blank=True, max_length=500, verbose_name='仓库路径')),
                ('samples_folder', models.CharField(default='LifeSamples', max_length=200, verbose_name='样本文件夹')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'obsidian_config',
            },
        ),
    ]
