# Generated by Django 6.0.4 on 2026-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifesample',
            name='obsidian_path',
            field=models.CharField(blank=True, help_text='相对于Obsidian仓库根目录，如：05_人生样本(LifeSamples)/曾国藩.md', max_length=500, verbose_name='Obsidian文件路径'),
        ),
        migrations.AlterField(
            model_name='obsidianconfig',
            name='samples_folder',
            field=models.CharField(default='05_人生样本(LifeSamples)', max_length=200, verbose_name='样本文件夹'),
        ),
    ]
