# Generated by Django 6.0.4 on 2026-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesample', '0002_alter_lifesample_obsidian_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifesample',
            name='relevance',
            field=models.CharField(choices=[('high', '🔥 高度借鉴'), ('reference', '📖 参考'), ('knowledge', '👀 了解')], default='knowledge', max_length=20, verbose_name='借鉴意义'),
        ),
        migrations.AddField(
            model_name='lifesample',
            name='relevance_reason',
            field=models.CharField(blank=True, help_text='为什么这个样本对你有这个级别的借鉴意义', max_length=200, verbose_name='评级理由'),
        ),
        migrations.AddField(
            model_name='lifesample',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审阅时间'),
        ),
        migrations.AddField(
            model_name='lifesample',
            name='status',
            field=models.CharField(choices=[('collected', '📥 已收集'), ('verified', '🔍 已核实'), ('reviewed', '✅ 已审阅')], default='collected', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='lifesample',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核实时间'),
        ),
    ]
