# Generated by Django 6.0.4 on 2026-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifesample', '0003_lifesample_relevance_lifesample_relevance_reason_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lifesample',
            index=models.Index(fields=['obsidian_path'], name='idx_ls_obsidian_path'),
        ),
        migrations.AddConstraint(
            model_name='lifesample',
            constraint=models.UniqueConstraint(fields=('obsidian_path',), name='uq_ls_obsidian_path'),
        ),
    ]
