# Generated by Django 6.0.4 on 2026-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SugarRecord',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('years', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='月份')),
                ('title', models.CharField(max_length=100, verbose_name='小确幸标题')),
                ('level_of_happiness', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='快乐程度 1.0-10.0')),
                ('time', models.DateField(verbose_name='发生日期')),
                ('category', models.CharField(blank=True, choices=[('food', '美食'), ('travel', '旅行'), ('learn', '学习'), ('social', '社交'), ('leisure', '休闲'), ('work', '工作'), ('health', '健康'), ('other', '其他')], max_length=20, null=True, verbose_name='分类')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='标签，逗号分隔')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本记录产生的奖励金额')),
                ('reward_synced', models.BooleanField(default=False, verbose_name='奖励是否已同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小确幸记录',
                'verbose_name_plural': '小确幸记录',
                'db_table': 'sugar_record',
                'ordering': ['-time', '-s_id'],
                'indexes': [models.Index(fields=['time'], name='sugar_recor_time_9db9f8_idx'), models.Index(fields=['level_of_happiness'], name='sugar_recor_level_o_9a5721_idx'), models.Index(fields=['category'], name='sugar_recor_categor_356640_idx'), models.Index(fields=['years', 'month'], name='sugar_recor_years_f5d2f6_idx')],
            },
        ),
    ]
