# Generated by Django 6.0.4 on 2026-05-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('stat_date', models.DateField(verbose_name='统计日期')),
                ('total_energy', models.IntegerField(default=0, verbose_name='当日总能量')),
                ('completed_count', models.IntegerField(default=0, verbose_name='完成数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日能量统计',
                'verbose_name_plural': '每日能量统计',
                'db_table': 'sugar_energy_daily_stats',
                'unique_together': {('user_id', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='EnergyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='内容描述')),
                ('default_energy', models.IntegerField(default=1, verbose_name='默认能量值（1-5）')),
                ('category', models.CharField(choices=[('daily', '日常'), ('creative', '创意'), ('social', '社交'), ('relax', '放松')], default='daily', max_length=50, verbose_name='分类')),
                ('icon', models.CharField(default='☀️', max_length=10, verbose_name='图标')),
                ('estimated_seconds', models.IntegerField(default=60, verbose_name='预估耗时（秒）')),
                ('is_system', models.BooleanField(default=True, verbose_name='是否系统预设')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID（自定义时填写）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '能量清单模板',
                'verbose_name_plural': '能量清单模板',
                'db_table': 'sugar_energy_template',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['user_id'], name='sugar_energ_user_id_9fc5a2_idx'), models.Index(fields=['category'], name='sugar_energ_categor_2afb3f_idx'), models.Index(fields=['is_active'], name='sugar_energ_is_acti_a14aaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='实际内容')),
                ('energy_gained', models.IntegerField(default=1, verbose_name='获得的能量值')),
                ('is_custom', models.BooleanField(default=False, verbose_name='是否自定义内容')),
                ('completed_at', models.DateTimeField(verbose_name='完成时间')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('reward_processed', models.BooleanField(default=False, verbose_name='是否已处理奖励池')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('template', models.ForeignKey(blank=True, db_column='template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sugar.energytemplate', verbose_name='关联模板')),
            ],
            options={
                'verbose_name': '能量清单完成记录',
                'verbose_name_plural': '能量清单完成记录',
                'db_table': 'sugar_energy_log',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user_id', 'completed_at'], name='sugar_energ_user_id_e4fea7_idx'), models.Index(fields=['user_id', 'reward_processed'], name='sugar_energ_user_id_bcf600_idx')],
            },
        ),
    ]
