# Generated by Django 6.0.4 on 2026-05-09 12:29

from django.db import migrations


def insert_presets(apps, schema_editor):
    EnergyTemplate = apps.get_model('sugar', 'EnergyTemplate')
    presets = [
        ('给绿植浇水', 1, 'daily', '🌱', 30, 1),
        ('喝一杯温水', 1, 'daily', '💧', 10, 2),
        ('站起来拉伸1分钟', 1, 'daily', '🧘', 60, 3),
        ('整理一个抽屉', 3, 'daily', '🗄️', 300, 4),
        ('拍一张天空/窗外', 2, 'creative', '📸', 10, 5),
        ('听一首喜欢的歌', 2, 'relax', '🎵', 180, 6),
        ('对镜子笑一下', 1, 'daily', '😊', 5, 7),
        ('写一句“今天我感谢...”', 3, 'creative', '✍️', 120, 8),
        ('给朋友发一条问候', 2, 'social', '💬', 60, 9),
        ('看一页书', 1, 'daily', '📖', 120, 10),
        ('深呼吸3次', 1, 'relax', '🌬️', 10, 11),
        ('走楼梯代替电梯', 2, 'daily', '🚶', 60, 12),
        ('关掉手机通知30分钟', 3, 'relax', '📵', 1800, 13),
        ('整理一张照片到DAMS', 2, 'creative', '🖼️', 60, 14),
        ('记录今天的一个小确幸', 3, 'creative', '✨', 120, 15),
    ]
    for content, energy, category, icon, seconds, sort in presets:
        EnergyTemplate.objects.create(
            content=content, default_energy=energy, category=category,
            icon=icon, estimated_seconds=seconds, sort_order=sort,
            is_system=True, is_active=True,
        )


def remove_presets(apps, schema_editor):
    EnergyTemplate = apps.get_model('sugar', 'EnergyTemplate')
    EnergyTemplate.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0002_energydailystats_energytemplate_energylog'),
    ]

    operations = [
        migrations.RunPython(insert_presets, remove_presets),
    ]
