# Generated by Django 6.0.4 on 2026-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0003_insert_energy_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID（预留）')),
                ('category', models.CharField(choices=[('daily', '日常'), ('creative', '创意'), ('social', '社交'), ('relax', '放松')], max_length=50, verbose_name='分类')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('icon', models.CharField(default='🌱', max_length=10, verbose_name='图标')),
                ('points', models.IntegerField(default=1, verbose_name='积分')),
                ('duration', models.CharField(default='1分钟', max_length=50, verbose_name='预估时长')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小确幸模板',
                'verbose_name_plural': '小确幸模板',
                'db_table': 'sugar_template',
                'ordering': ['category', 'sort_order'],
            },
        ),
    ]
