# Generated by Django 6.0.4 on 2026-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0004_add_sugar_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugarrecord',
            name='joy_type',
            field=models.CharField(blank=True, choices=[('创造', '🎨 创造'), ('社交', '💬 社交'), ('独处', '🧘 独处'), ('户外', '🌿 户外'), ('美食', '🍽️ 美食'), ('学习', '📚 学习'), ('其他', '✨ 其他')], default='', max_length=20, verbose_name='快乐类型'),
        ),
    ]
