# Generated by Django 6.0.4 on 2026-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0005_sugarrecord_joy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugarrecord',
            name='joy_type',
            field=models.CharField(blank=True, choices=[('感官型', '🌿 感官型'), ('秩序型', '📋 秩序型'), ('联结型', '💬 联结型'), ('意外型', '🎁 意外型'), ('独处型', '🧘 独处型')], default='', max_length=20, verbose_name='快乐类型'),
        ),
        migrations.AlterField(
            model_name='sugarrecord',
            name='level_of_happiness',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='快乐程度 5-20'),
        ),
    ]
