# Generated by Django 6.0.4 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS `health_step_info` (
                  `hid` int NOT NULL AUTO_INCREMENT,
                  `steps` int DEFAULT NULL COMMENT '步数',
                  `htype` int DEFAULT NULL COMMENT '运动类型：1步数, 2跳绳, 3跑步, 4骑行',
                  `cofficient` float DEFAULT NULL COMMENT '转换系数',
                  `total` float DEFAULT NULL COMMENT '折算后步数',
                  `time` datetime DEFAULT NULL COMMENT '运动时间',
                  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
                  `years` varchar(25) DEFAULT NULL COMMENT '年份',
                  `user_id` bigint DEFAULT NULL COMMENT '用户ID',
                  PRIMARY KEY (`hid`),
                  KEY `idx_time` (`time`),
                  KEY `idx_years` (`years`),
                  KEY `idx_htype` (`htype`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3
            """,
            reverse_sql="DROP TABLE IF EXISTS `health_step_info`",
            state_operations=[
                migrations.CreateModel(
                    name='HealthRecord',
                    fields=[
                        ('hid', models.AutoField(primary_key=True, serialize=False)),
                        ('steps', models.IntegerField(blank=True, null=True, verbose_name='步数')),
                        ('htype', models.IntegerField(blank=True, choices=[(1, '步数'), (2, '跳绳'), (3, '跑步'), (4, '骑行')], default=1, null=True, verbose_name='运动类型')),
                        ('cofficient', models.FloatField(blank=True, null=True, verbose_name='转换系数')),
                        ('total', models.FloatField(blank=True, null=True, verbose_name='折算后步数')),
                        ('time', models.DateTimeField(blank=True, null=True, verbose_name='运动时间')),
                        ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                        ('years', models.CharField(blank=True, max_length=25, null=True, verbose_name='年份')),
                        ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                    ],
                    options={
                        'verbose_name': '运动记录',
                        'verbose_name_plural': '运动记录',
                        'db_table': 'health_step_info',
                        'ordering': ['-time'],
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
