# Generated by Django 6.0.4 on 2026-05-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBodyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='用户ID')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='身高（厘米）')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户身体信息',
                'verbose_name_plural': '用户身体信息',
                'db_table': 'health_user_body_info',
            },
        ),
        migrations.CreateModel(
            name='WeightGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('target_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最终目标体重（公斤）')),
                ('start_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='起始体重（公斤）')),
                ('monthly_target_kg', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='每月目标减重（公斤）')),
                ('start_date', models.DateField(verbose_name='目标开始日期')),
                ('expected_end_date', models.DateField(blank=True, null=True, verbose_name='预计达成日期')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('abandoned', '已放弃')], default='in_progress', max_length=20, verbose_name='状态')),
                ('current_month', models.IntegerField(default=1, verbose_name='当前第几个月')),
                ('current_month_start_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='本月起始体重')),
                ('current_month_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='本月目标体重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否当前活跃目标')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='达成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '体重目标',
                'verbose_name_plural': '体重目标',
                'db_table': 'health_weight_goal',
                'indexes': [models.Index(fields=['user_id'], name='health_weig_user_id_ebab80_idx'), models.Index(fields=['is_active'], name='health_weig_is_acti_292570_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重（公斤）')),
                ('body_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='体脂率（%）')),
                ('measure_time', models.CharField(blank=True, choices=[('morning', '早晨'), ('afternoon', '下午'), ('evening', '晚上')], max_length=20, null=True, verbose_name='测量时间')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '体重记录',
                'verbose_name_plural': '体重记录',
                'db_table': 'health_weight_record',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['record_date'], name='health_weig_record__01cdbb_idx'), models.Index(fields=['user_id'], name='health_weig_user_id_64e337_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'record_date'), name='uk_weight_user_date')],
            },
        ),
        migrations.CreateModel(
            name='WeightMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField(verbose_name='第几个月')),
                ('start_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='月初体重')),
                ('target_weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='月目标体重')),
                ('end_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='月末实际体重')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='是否达成')),
                ('achieved_at', models.DateField(blank=True, null=True, verbose_name='达成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='health.weightgoal', verbose_name='关联目标')),
            ],
            options={
                'verbose_name': '月度里程碑',
                'verbose_name_plural': '月度里程碑',
                'db_table': 'health_weight_milestone',
                'ordering': ['month_number'],
                'indexes': [models.Index(fields=['goal'], name='health_weig_goal_id_ec9a1a_idx')],
            },
        ),
    ]
