# Generated by Django 6.0.4 on 2026-06-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_userbodyinfo_weightgoal_weightrecord_weightmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenstrualRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.CharField(max_length=10, verbose_name='月份')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('offset', models.IntegerField(default=0, verbose_name='偏移量(天)')),
                ('cycle_days', models.IntegerField(default=30, verbose_name='周期跨度(天)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '例假记录',
                'verbose_name_plural': '例假记录',
                'db_table': 'health_menstrual_record',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='health_mens_start_d_0224a5_idx'), models.Index(fields=['user_id'], name='health_mens_user_id_f0d5a8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'start_date'), name='uk_menstrual_user_date')],
            },
        ),
    ]
