# Generated by Django 6.0.4 on 2026-06-24 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_menstrualrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menstrualrecord',
            options={'ordering': ['-start_date'], 'verbose_name': '好朋友记录', 'verbose_name_plural': '好朋友记录'},
        ),
        migrations.CreateModel(
            name='WeightGoalAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('before_value', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='变更前目标(斤)')),
                ('after_value', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='变更后目标(斤)')),
                ('change_amount', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='调整值(斤)')),
                ('reason', models.TextField(blank=True, default='', verbose_name='调整原因')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='调整时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='health.weightgoal', verbose_name='关联目标')),
            ],
            options={
                'verbose_name': '目标调整记录',
                'verbose_name_plural': '目标调整记录',
                'db_table': 'health_weight_goal_adjustment',
                'ordering': ['-adjusted_at'],
            },
        ),
    ]
