# Generated by Django 6.0.4 on 2026-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_step_info_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='menstrualrecord',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='持续天数（自动=结束-开始，可手动覆盖）'),
        ),
        migrations.AddField(
            model_name='menstrualrecord',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='本次结束日期'),
        ),
    ]
