# Generated by Django 6.0.4 on 2026-05-03 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('years', models.CharField(blank=True, max_length=25, null=True, verbose_name='年度')),
                ('btitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='书名标题')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('original_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='原著书名')),
                ('btype', models.CharField(blank=True, choices=[('基础学科', '基础学科'), ('哲学智慧', '哲学智慧'), ('心理健康', '心理健康'), ('财富创造', '财富创造'), ('幸福科学', '幸福科学'), ('认知提升类', '认知提升类'), ('技能工具类', '技能工具类'), ('文学滋养类', '文学滋养类'), ('休闲放松类', '休闲放松类'), ('个人成长类', '个人成长类'), ('能量消耗类', '能量消耗类')], max_length=50, null=True, verbose_name='书籍类型')),
                ('status', models.CharField(blank=True, choices=[('计划阅读', '计划阅读'), ('在读', '在读'), ('精读', '精读'), ('通读', '通读'), ('消遣', '消遣'), ('弃读', '弃读'), ('已完成', '已完成'), ('待重读', '待重读')], max_length=25, null=True, verbose_name='状态')),
                ('recommend', models.IntegerField(choices=[(0, '禁止阅读'), (1, '不推荐'), (2, '一般'), (3, '推荐'), (4, '宝藏'), (5, '人生必读')], default=0, verbose_name='推荐指数')),
                ('reading_depth', models.IntegerField(blank=True, choices=[(1, '速读浏览'), (2, '重点阅读'), (3, '精读细品'), (4, '反复研读'), (5, '践行内化')], default=3, null=True, verbose_name='阅读深度')),
                ('readDate', models.DateField(blank=True, null=True, verbose_name='阅读日期')),
                ('created_at', models.DateField(db_column='createDate', default=datetime.date.today, verbose_name='创建日期')),
                ('updated_at', models.DateField(auto_now=True, db_column='updateDate', verbose_name='更新日期')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='标签')),
                ('abandon_reason', models.TextField(blank=True, null=True, verbose_name='弃读原因')),
                ('closedop', models.TextField(blank=True, null=True, verbose_name='读后感')),
                ('openop', models.TextField(blank=True, null=True, verbose_name='打开书时的观点和期待')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID（预留）')),
            ],
            options={
                'verbose_name': '书籍阅读记录',
                'verbose_name_plural': '书籍阅读记录',
                'db_table': 'book_read_list',
                'ordering': ['-readDate'],
            },
        ),
    ]
