# Generated by Django 6.0.4 on 2026-05-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='action_item',
            field=models.TextField(blank=True, default='', help_text='读完这本书后决定做的一件事', verbose_name='行动项'),
        ),
    ]
