# Generated by Django 6.0.4 on 2026-08-27 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_action_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
