# Generated by Django 6.0.4 on 2026-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(max_length=50, verbose_name='来源模块')),
                ('source_object_id', models.IntegerField(blank=True, null=True, verbose_name='来源对象ID')),
                ('category', models.CharField(choices=[('reminder', '提醒'), ('alert', '警告'), ('info', '信息')], max_length=20, verbose_name='通知类别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='内容')),
                ('action_url', models.CharField(blank=True, max_length=200, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
