# Generated by Django 6.0.4 on 2026-08-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_userprofile'), ('core', '0003_userprofile_logseq_path'), ('core', '0004_systempreset')]


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_module', models.CharField(max_length=50, verbose_name='来源模块')),
                ('source_object_id', models.IntegerField(blank=True, null=True, verbose_name='来源对象ID')),
                ('category', models.CharField(choices=[('reminder', '提醒'), ('alert', '警告'), ('info', '信息')], max_length=20, verbose_name='通知类别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='内容')),
                ('action_url', models.CharField(blank=True, max_length=200, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统通知',
                'verbose_name_plural': '系统通知',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, unique=True, verbose_name='用户ID')),
                ('privacy_mode', models.BooleanField(default=False, verbose_name='脱敏模式')),
                ('logseq_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Logseq 日记目录')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
                'db_table': 'core_user_profile',
            },
        ),
        migrations.CreateModel(
            name='SystemPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_type', models.CharField(choices=[('tags', '标签预设'), ('quick_phrases', '快捷短语（里程碑完成感悟）'), ('sugar_tags', '小确幸预设标签'), ('diary_tags', '日记流预设标签')], max_length=50, unique=True, verbose_name='预设类型')),
                ('values', models.JSONField(blank=True, default=list, verbose_name='预设值列表')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统预设',
                'verbose_name_plural': '系统预设',
                'db_table': 'core_system_preset',
                'unique_together': {('preset_type',)},
            },
        ),
    ]
