# Generated by Django 6.0.4 on 2026-05-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, unique=True, verbose_name='用户ID')),
                ('privacy_mode', models.BooleanField(default=False, verbose_name='脱敏模式')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
                'db_table': 'core_user_profile',
            },
        ),
    ]
