# Generated by Django 6.0.4 on 2026-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logseq_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Logseq 日记目录'),
        ),
    ]
