# Generated by Django 6.0.4 on 2026-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_logseq_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_type', models.CharField(choices=[('tags', '标签预设'), ('quick_phrases', '快捷短语（里程碑完成感悟）'), ('sugar_tags', '小确幸预设标签'), ('diary_tags', '日记流预设标签')], max_length=50, unique=True, verbose_name='预设类型')),
                ('values', models.JSONField(blank=True, default=list, verbose_name='预设值列表')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统预设',
                'verbose_name_plural': '系统预设',
                'db_table': 'core_system_preset',
                'unique_together': {('preset_type',)},
            },
        ),
    ]
