# Generated by Django 6.0.4 on 2026-08-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=50, unique=True, verbose_name='分组标识')),
                ('group_name', models.CharField(max_length=50, verbose_name='分组名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜单分组',
                'verbose_name_plural': '菜单分组',
                'db_table': 'core_menu_group',
                'ordering': ['sort_order', 'group_key'],
            },
        ),
        migrations.CreateModel(
            name='MenuPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('menu_key', models.CharField(max_length=100, unique=True, verbose_name='菜单标识')),
                ('is_favorite', models.BooleanField(default=True, verbose_name='是否常用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '菜单偏好',
                'verbose_name_plural': '菜单偏好',
                'db_table': 'core_menu_preference',
                'ordering': ['sort_order', 'menu_key'],
            },
        ),
    ]
