# Generated by Django 6.0.4 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS `relationship_relationship` (
                  `id` int NOT NULL AUTO_INCREMENT,
                  `name` varchar(100) NOT NULL COMMENT '姓名/昵称',
                  `alias` varchar(200) DEFAULT '' COMMENT '曾用名/绰号',
                  `met_date` date DEFAULT NULL COMMENT '认识时间',
                  `met_place` varchar(200) DEFAULT '' COMMENT '认识地点',
                  `met_scene` text COMMENT '认识场景',
                  `identity_then` varchar(200) DEFAULT '' COMMENT '当时身份',
                  `they_give_me` text COMMENT '他能给我什么',
                  `i_give_them` text COMMENT '我能给他什么',
                  `current_status` varchar(20) DEFAULT 'active' COMMENT '当前状态',
                  `current_quality` varchar(20) DEFAULT 'neutral' COMMENT '关系质量',
                  `notes` text COMMENT '备注',
                  `tags` varchar(200) DEFAULT '' COMMENT '标签',
                  `user_id` int NOT NULL COMMENT '用户ID',
                  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
                  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                  PRIMARY KEY (`id`),
                  KEY `idx_user_id` (`user_id`),
                  KEY `idx_current_quality` (`current_quality`),
                  KEY `idx_current_status` (`current_status`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='关系档案表';

                CREATE TABLE IF NOT EXISTS `relationship_interaction` (
                  `id` int NOT NULL AUTO_INCREMENT,
                  `relationship_id` int NOT NULL COMMENT '关联的关系ID',
                  `happened_at` datetime NOT NULL COMMENT '互动时间',
                  `method` varchar(20) DEFAULT '' COMMENT '方式：meet/call/wechat/other',
                  `energy_score` smallint NOT NULL COMMENT '能量分：-10到+10',
                  `summary` varchar(200) DEFAULT '' COMMENT '一句话总结',
                  `quality_shift` varchar(20) DEFAULT '' COMMENT '质量变化：improved/declined/same',
                  `next_reminder` varchar(200) DEFAULT '' COMMENT '下次可以做什么',
                  `user_id` int NOT NULL COMMENT '用户ID',
                  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
                  PRIMARY KEY (`id`),
                  KEY `idx_relationship_id` (`relationship_id`),
                  KEY `idx_happened_at` (`happened_at`),
                  KEY `idx_user_id` (`user_id`),
                  CONSTRAINT `fk_interaction_relationship`
                    FOREIGN KEY (`relationship_id`) REFERENCES `relationship_relationship` (`id`)
                    ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='互动记录表';
            """,
            reverse_sql="""
                DROP TABLE IF EXISTS `relationship_interaction`;
                DROP TABLE IF EXISTS `relationship_relationship`;
            """,
            state_operations=[
                migrations.CreateModel(
                    name='Relationship',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('name', models.CharField(max_length=100, verbose_name='姓名/昵称')),
                        ('alias', models.CharField(blank=True, default='', max_length=200, verbose_name='曾用名/绰号')),
                        ('met_date', models.DateField(blank=True, null=True, verbose_name='认识时间')),
                        ('met_place', models.CharField(blank=True, default='', max_length=200, verbose_name='认识地点')),
                        ('met_scene', models.TextField(blank=True, default='', verbose_name='认识场景')),
                        ('identity_then', models.CharField(blank=True, default='', max_length=200, verbose_name='当时身份')),
                        ('they_give_me', models.TextField(blank=True, default='', verbose_name='他能给我什么')),
                        ('i_give_them', models.TextField(blank=True, default='', verbose_name='我能给他什么')),
                        ('current_status', models.CharField(choices=[('active', '保持联系'), ('distant', '已疏远'), ('paused', '暂停联系'), ('ended', '已结束')], default='active', max_length=20, verbose_name='当前状态')),
                        ('current_quality', models.CharField(choices=[('nourishing', '滋养型'), ('neutral', '中性'), ('draining', '消耗型'), ('toxic', '有害型')], default='neutral', max_length=20, verbose_name='关系质量')),
                        ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                        ('tags', models.CharField(blank=True, default='', max_length=200, verbose_name='标签')),
                        ('user_id', models.IntegerField(verbose_name='用户ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                    ],
                    options={
                        'verbose_name': '关系档案',
                        'verbose_name_plural': '关系档案',
                        'db_table': 'relationship_relationship',
                        'ordering': ['-updated_at'],
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='Interaction',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('relationship', models.ForeignKey(db_column='relationship_id', on_delete=models.deletion.CASCADE, related_name='interactions', to='relation.Relationship', verbose_name='关联关系')),
                        ('happened_at', models.DateTimeField(verbose_name='互动时间')),
                        ('method', models.CharField(blank=True, choices=[('meet', '☕ 见面'), ('call', '📞 电话'), ('wechat', '💬 微信'), ('other', '📧 其他')], default='', max_length=20, verbose_name='方式')),
                        ('energy_score', models.IntegerField(verbose_name='能量分（-10 到 +10）')),
                        ('summary', models.CharField(blank=True, default='', max_length=200, verbose_name='一句话总结')),
                        ('quality_shift', models.CharField(blank=True, choices=[('improved', '感觉变好了'), ('declined', '感觉变差了'), ('same', '差不多')], default='', max_length=20, verbose_name='质量变化')),
                        ('next_reminder', models.CharField(blank=True, default='', max_length=200, verbose_name='下次可以做什么')),
                        ('user_id', models.IntegerField(verbose_name='用户ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                    ],
                    options={
                        'verbose_name': '互动记录',
                        'verbose_name_plural': '互动记录',
                        'db_table': 'relationship_interaction',
                        'ordering': ['-happened_at'],
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
