# Generated by Django 6.0.4 on 2026-05-10 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('name', models.CharField(max_length=100, verbose_name='群体名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('total_energy', models.IntegerField(default=0, verbose_name='总能量分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '读者群体',
                'verbose_name_plural': '读者群体',
                'db_table': 'relation_reader_group',
            },
        ),
        migrations.CreateModel(
            name='ReaderInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('reader_name', models.CharField(max_length=100, verbose_name='读者昵称')),
                ('interaction_type', models.CharField(choices=[('comment', '💬 留言'), ('like', '❤️ 点赞'), ('share', '🔄 转发'), ('reward', '💰 打赏')], max_length=20, verbose_name='互动类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='互动内容')),
                ('article_title', models.CharField(blank=True, default='', max_length=255, verbose_name='关联文章')),
                ('energy_score', models.IntegerField(default=1, verbose_name='能量分')),
                ('tags', models.CharField(blank=True, default='', max_length=500, verbose_name='共振关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reader_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='relation.readergroup', verbose_name='所属群体')),
            ],
            options={
                'verbose_name': '读者互动',
                'verbose_name_plural': '读者互动',
                'db_table': 'relation_reader_interaction',
                'ordering': ['-energy_score', '-created_at'],
            },
        ),
    ]
