# Generated by Django 6.0.4 on 2026-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_readergroup_readerinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerinteraction',
            name='interaction_date',
            field=models.DateField(blank=True, help_text='不填默认为创建日期', null=True, verbose_name='互动时间'),
        ),
        migrations.AlterField(
            model_name='readerinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('comment', '💬 留言'), ('like', '❤️ 点赞'), ('share', '🔄 转发'), ('follow', '➕ 关注'), ('unfollow', '➖ 取关'), ('reward', '💰 打赏')], max_length=20, verbose_name='互动类型'),
        ),
    ]
