# Generated by Django 6.0.4 on 2026-06-02 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0004_interaction_my_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='事件描述')),
                ('event_type', models.CharField(default='其他', max_length=30, verbose_name='事件类型')),
                ('emotion_level', models.IntegerField(default=1, help_text='1=轻微不爽, 5=极度愤怒', verbose_name='愤怒指数')),
                ('loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='经济损失(元)')),
                ('loss_time', models.CharField(blank=True, default='', max_length=50, verbose_name='时间成本')),
                ('event_date', models.DateField(verbose_name='发生日期')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='解决备注')),
                ('tags', models.CharField(blank=True, default='', max_length=200, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='relation.relationship', verbose_name='关联联系人')),
            ],
            options={
                'verbose_name': '冲突事件',
                'db_table': 'relation_conflict_event',
                'ordering': ['-event_date'],
            },
        ),
    ]
