# Generated by Django 6.0.4 on 2026-06-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0005_conflictevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderMonthlySummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('new_followers', models.IntegerField(default=0, verbose_name='本月新增关注')),
                ('new_unfollowers', models.IntegerField(default=0, verbose_name='本月取关')),
                ('total_followers', models.IntegerField(default=0, verbose_name='截至本月总关注')),
                ('total_interactions', models.IntegerField(default=0, verbose_name='本月互动总量')),
                ('high_energy_count', models.IntegerField(default=0, verbose_name='本月高能量互动数')),
                ('top_article', models.CharField(blank=True, default='', max_length=255, verbose_name='本月最佳文章')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reader_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='relation.readergroup', verbose_name='所属群体')),
            ],
            options={
                'verbose_name': '读者月末盘点',
                'db_table': 'relation_reader_monthly_summary',
                'ordering': ['-year', '-month'],
                'unique_together': {('reader_group', 'year', 'month')},
            },
        ),
    ]
