# Generated by Django 6.0.4 on 2026-08-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_readermonthlysummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflictevent',
            options={'ordering': ['-event_date'], 'verbose_name': '成长记录'},
        ),
    ]
