# Generated by Django 6.0.4 on 2026-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当前余额')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计获得')),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计提取')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '奖励池',
                'verbose_name_plural': '奖励池',
                'db_table': 'reward_pool',
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='流水ID')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='来源ID')),
                ('source_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='来源类型(milestone/sugar)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('transaction_type', models.CharField(choices=[('milestone_complete', '里程碑完成'), ('milestone_update', '里程碑修改'), ('milestone_delete', '里程碑删除'), ('sugar_create', '小确幸'), ('withdraw', '提取')], max_length=50, verbose_name='交易类型')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易前余额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='交易后余额')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '奖励流水',
                'verbose_name_plural': '奖励流水',
                'db_table': 'reward_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
