# Generated by Django 6.0.4 on 2026-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('milestone_complete', '里程碑完成'), ('milestone_update', '里程碑修改'), ('milestone_delete', '里程碑删除'), ('sugar_create', '小确幸'), ('sugar_update', '小确幸修改'), ('sugar_delete', '小确幸删除'), ('gift_exchange', '礼物兑换'), ('withdraw', '提取')], max_length=50, verbose_name='交易类型'),
        ),
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='礼物名称')),
                ('expected_reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预期价格')),
                ('actual_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际兑换价格')),
                ('status', models.CharField(choices=[('pending', '待兑换'), ('waiting', '可兑换'), ('redeemed', '已兑换'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('category', models.CharField(blank=True, choices=[('physical', '实物'), ('experience', '体验'), ('virtual', '虚拟'), ('other', '其他')], max_length=50, null=True, verbose_name='分类')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级(越小越优先)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='图片链接')),
                ('link_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='购买链接')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='兑换时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '礼物清单',
                'verbose_name_plural': '礼物清单',
                'db_table': 'reward_gift_list',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='reward_gift_status_763ba5_idx'), models.Index(fields=['priority'], name='reward_gift_priorit_1b065d_idx')],
            },
        ),
    ]
