# Generated by Django 6.0.4 on 2026-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_alter_rewardtransaction_transaction_type_giftlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('milestone_complete', '里程碑完成'), ('milestone_update', '里程碑修改'), ('milestone_delete', '里程碑删除'), ('sugar_create', '小确幸'), ('sugar_update', '小确幸修改'), ('sugar_delete', '小确幸删除'), ('gift_exchange', '礼物兑换'), ('withdraw', '提取'), ('inbox_complete', '收件箱完成')], max_length=50, verbose_name='交易类型'),
        ),
    ]
