# Generated by Django 6.0.4 on 2026-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_add_goal_complete_tx_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['transaction_type'], name='idx_reward_type'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='idx_reward_source'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['created_at'], name='idx_reward_created'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='idx_reward_type_created'),
        ),
    ]
