# Generated by Django 6.0.4 on 2026-08-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('goals', '0001_initial'), ('goals', '0002_alter_action_options_remove_action_completed_date_and_more'), ('goals', '0003_rebuild_action'), ('goals', '0004_rename_goals_acti_goal_id_43c5d6_idx_goals_actio_goal_id_61b6db_idx_and_more'), ('goals', '0005_action_completion_log_action_is_active'), ('goals', '0006_outputrecord'), ('goals', '0007_action_action_date'), ('goals', '0008_milestone_description'), ('goals', '0009_milestone_self_review'), ('goals', '0010_goal_parent_goal'), ('goals', '0011_goal_life_dimension_milestone_difficulty_met_and_more'), ('goals', '0012_alter_goal_life_dimension'), ('goals', '0013_add_goal_completion_bonus'), ('goals', '0014_make_life_dimension_required'), ('goals', '0015_alter_goal_category')]


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='目标ID')),
                ('title', models.CharField(max_length=255, verbose_name='目标标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='目标描述')),
                ('category', models.CharField(choices=[('year', '年度目标'), ('quarter', '季度目标'), ('month', '月度目标'), ('long-term', '长期目标'), ('project', '项目目标')], max_length=50, verbose_name='目标类型')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='目标标签')),
                ('priority', models.CharField(choices=[('p0', 'P0 - 紧急重要'), ('p1', 'P1 - 重要'), ('p2', 'P2 - 一般'), ('p3', 'P3 - 低优先级')], default='p2', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('planning', '计划中'), ('in-progress', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('abandoned', '已放弃'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态')),
                ('progress_percentage', models.IntegerField(default=0, editable=False, verbose_name='进度百分比')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('life_dimension', models.CharField(choices=[('身体健康', '🏃 身体健康'), ('财富积累', '💰 财富积累'), ('学习成长', '📚 学习成长'), ('事业发展', '💼 事业发展'), ('休闲放松', '🌿 休闲放松'), ('系统建设', '🧰 系统建设'), ('创作输出', '🎨 创作输出'), ('生活空间', '🏠 生活空间'), ('其他事项', '✨ 其他事项')], max_length=20, verbose_name='人生维度')),
                ('decision_quality', models.IntegerField(blank=True, null=True, verbose_name='决策质量评分(1-10)')),
                ('mental_models_used', models.CharField(blank=True, max_length=500, null=True, verbose_name='使用的思维模型')),
                ('inversion_check', models.TextField(blank=True, null=True, verbose_name='逆向思考检查')),
                ('first_principles', models.TextField(blank=True, null=True, verbose_name='第一性原理分析')),
                ('circle_check', models.IntegerField(blank=True, null=True, verbose_name='是否在能力圈内')),
                ('happiness_impact', models.IntegerField(blank=True, null=True, verbose_name='幸福影响评分')),
                ('peace_impact', models.IntegerField(blank=True, null=True, verbose_name='内心平静影响评分')),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='每个里程碑的奖励额度')),
                ('enable_reward', models.BooleanField(default=False, verbose_name='是否启用里程碑奖励')),
                ('default_reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='每项里程碑奖励')),
                ('goal_completion_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='目标完成奖励金')),
                ('total_reward_issued', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本目标已发放奖励总额')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID（预留）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goals', to='goals.goal', verbose_name='父目标')),
            ],
            options={
                'verbose_name': '目标',
                'verbose_name_plural': '目标',
                'db_table': 'goals_goal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='回顾ID')),
                ('review_type', models.CharField(choices=[('weekly', '周回顾'), ('monthly', '月回顾'), ('milestone', '里程碑完成时')], default='weekly', max_length=20, verbose_name='回顾类型')),
                ('review_date', models.DateField(verbose_name='回顾日期')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分(1-10)')),
                ('what_worked', models.TextField(blank=True, verbose_name='做得好的')),
                ('what_blocked', models.TextField(blank=True, verbose_name='遇到的阻碍')),
                ('next_adjustment', models.TextField(blank=True, verbose_name='下一步调整')),
                ('content', models.TextField(blank=True, verbose_name='回顾内容')),
                ('progress_note', models.TextField(blank=True, null=True, verbose_name='进度说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goals.goal', verbose_name='所属目标')),
            ],
            options={
                'verbose_name': '目标回顾',
                'verbose_name_plural': '目标回顾',
                'db_table': 'goals_review',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='里程碑ID')),
                ('title', models.CharField(max_length=255, verbose_name='里程碑标题')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in-progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('completed_note', models.TextField(blank=True, null=True, verbose_name='完成备注说明')),
                ('self_review', models.TextField(blank=True, default='', verbose_name='自我批阅')),
                ('difficulty_met', models.TextField(blank=True, default='', verbose_name='遇到的困难')),
                ('next_action', models.TextField(blank=True, default='', verbose_name='下一步行动')),
                ('description', models.TextField(blank=True, default='', verbose_name='详细描述')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序序号')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='目标值')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际值')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='里程碑奖励金额')),
                ('reward_synced', models.BooleanField(default=False, verbose_name='奖励是否已同步')),
                ('reward_issued_at', models.DateTimeField(blank=True, null=True, verbose_name='奖励发放时间')),
                ('reward_transaction_id', models.IntegerField(blank=True, null=True, verbose_name='关联的奖励流水ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.goal', verbose_name='所属目标')),
            ],
            options={
                'verbose_name': '里程碑',
                'verbose_name_plural': '里程碑',
                'db_table': 'goals_milestone',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='行为ID')),
                ('name', models.CharField(max_length=200, verbose_name='行为名称')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注说明')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='发生日期')),
                ('completion_log', models.JSONField(blank=True, default=dict, verbose_name='打卡记录')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='goals.goal', verbose_name='所属目标')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='goals.milestone', verbose_name='关联里程碑')),
            ],
            options={
                'verbose_name': '行为记录',
                'verbose_name_plural': '行为记录',
                'db_table': 'goals_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutputRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('title', models.CharField(max_length=200, verbose_name='事项名称')),
                ('category', models.CharField(choices=[('work', '工作'), ('writing', '写作'), ('social', '社交'), ('study', '学习'), ('health', '健康'), ('life', '生活'), ('other', '其他')], default='other', max_length=50, verbose_name='类别')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('quality', models.CharField(choices=[('good', '良品'), ('defective', '不良品'), ('waste', '废品')], max_length=20, verbose_name='质量判定')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1=轻车熟路, 5=完全未知', verbose_name='难度')),
                ('fail_reason', models.TextField(blank=True, verbose_name='失败原因（不良品/废品时填写）')),
                ('fail_type', models.CharField(blank=True, choices=[('cognitive', '认知盲区'), ('ability', '能力不足'), ('external', '外部因素'), ('luck', '运气'), ('careless', '粗心'), ('other', '其他')], max_length=50, verbose_name='失败类型')),
                ('lesson_learned', models.TextField(blank=True, verbose_name='经验教训')),
                ('occurred_at', models.DateField(blank=True, null=True, verbose_name='发生日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产出记录',
                'verbose_name_plural': '产出记录',
                'db_table': 'goals_output_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='goals_outpu_user_id_bc4881_idx'), models.Index(fields=['quality'], name='goals_outpu_quality_7aed5e_idx'), models.Index(fields=['category'], name='goals_outpu_categor_423939_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['year'], name='goals_goal_year_067254_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['category'], name='goals_goal_categor_07c7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status'], name='goals_goal_status_ea0ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['deadline'], name='goals_goal_deadlin_309c22_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['goal', 'created_at'], name='goals_actio_goal_id_61b6db_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['goal', 'milestone'], name='goals_actio_goal_id_ddb3f1_idx'),
        ),
    ]
