# Generated by Django 6.0.4 on 2026-05-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='目标ID')),
                ('title', models.CharField(max_length=255, verbose_name='目标标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='目标描述')),
                ('category', models.CharField(choices=[('year', '年度目标'), ('quarter', '季度目标'), ('month', '月度目标'), ('long-term', '长期目标')], max_length=50, verbose_name='目标类型')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='目标标签')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('not-started', '未开始'), ('in-progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停'), ('overdue', '已超期')], default='not-started', max_length=20, verbose_name='状态')),
                ('progress_percentage', models.IntegerField(default=0, editable=False, verbose_name='进度百分比')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('decision_quality', models.IntegerField(blank=True, null=True, verbose_name='决策质量评分(1-10)')),
                ('mental_models_used', models.CharField(blank=True, max_length=500, null=True, verbose_name='使用的思维模型')),
                ('inversion_check', models.TextField(blank=True, null=True, verbose_name='逆向思考检查')),
                ('first_principles', models.TextField(blank=True, null=True, verbose_name='第一性原理分析')),
                ('circle_check', models.IntegerField(blank=True, null=True, verbose_name='是否在能力圈内')),
                ('happiness_impact', models.IntegerField(blank=True, null=True, verbose_name='幸福影响评分')),
                ('peace_impact', models.IntegerField(blank=True, null=True, verbose_name='内心平静影响评分')),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='每个里程碑的奖励额度')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID（预留）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '目标',
                'verbose_name_plural': '目标',
                'db_table': 'goals_goal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['year'], name='goals_goal_year_067254_idx'), models.Index(fields=['category'], name='goals_goal_categor_07c7bc_idx'), models.Index(fields=['status'], name='goals_goal_status_ea0ea8_idx'), models.Index(fields=['deadline'], name='goals_goal_deadlin_309c22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='打卡ID')),
                ('title', models.CharField(max_length=255, verbose_name='行为标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='行为描述')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='打卡日期')),
                ('note', models.TextField(blank=True, null=True, verbose_name='打卡备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='goals.goal', verbose_name='所属目标')),
            ],
            options={
                'verbose_name': '行为打卡',
                'verbose_name_plural': '行为打卡',
                'db_table': 'goals_action',
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='回顾ID')),
                ('review_date', models.DateField(verbose_name='回顾日期')),
                ('content', models.TextField(verbose_name='回顾内容')),
                ('progress_note', models.TextField(blank=True, null=True, verbose_name='进度说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goals.goal', verbose_name='所属目标')),
            ],
            options={
                'verbose_name': '目标回顾',
                'verbose_name_plural': '目标回顾',
                'db_table': 'goals_review',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='里程碑ID')),
                ('title', models.CharField(max_length=255, verbose_name='里程碑标题')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_note', models.TextField(blank=True, null=True, verbose_name='完成备注说明')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='goals.goal', verbose_name='所属目标')),
            ],
            options={
                'verbose_name': '里程碑',
                'verbose_name_plural': '里程碑',
                'db_table': 'goals_milestone',
                'ordering': ['order_num', 'id'],
            },
        ),
    ]
