# Generated by Django 6.0.4 on 2026-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created_at'], 'verbose_name': '行为打卡', 'verbose_name_plural': '行为打卡'},
        ),
        migrations.RemoveField(
            model_name='action',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='action',
            name='note',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='completed',
        ),
        migrations.AddField(
            model_name='action',
            name='completion_log',
            field=models.JSONField(blank=True, default=list, verbose_name='打卡记录'),
        ),
        migrations.AddField(
            model_name='action',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='当前连续天数'),
        ),
        migrations.AddField(
            model_name='action',
            name='frequency_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='频率配置'),
        ),
        migrations.AddField(
            model_name='action',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='最长连续天数'),
        ),
        migrations.AddField(
            model_name='goalreview',
            name='next_adjustment',
            field=models.TextField(blank=True, verbose_name='下一步调整'),
        ),
        migrations.AddField(
            model_name='goalreview',
            name='review_type',
            field=models.CharField(choices=[('weekly', '周回顾'), ('monthly', '月回顾'), ('milestone', '里程碑完成时')], default='weekly', max_length=20, verbose_name='回顾类型'),
        ),
        migrations.AddField(
            model_name='goalreview',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分(1-10)'),
        ),
        migrations.AddField(
            model_name='goalreview',
            name='what_blocked',
            field=models.TextField(blank=True, verbose_name='遇到的阻碍'),
        ),
        migrations.AddField(
            model_name='goalreview',
            name='what_worked',
            field=models.TextField(blank=True, verbose_name='做得好的'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际值'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', '待开始'), ('in-progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='目标日期'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='目标值'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('p0', 'P0 - 紧急重要'), ('p1', 'P1 - 重要'), ('p2', 'P2 - 一般'), ('p3', 'P3 - 低优先级')], default='p2', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('planning', '计划中'), ('in-progress', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='goalreview',
            name='content',
            field=models.TextField(blank=True, verbose_name='回顾内容'),
        ),
    ]
