# Generated by Django 6.0.4 on 2026-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rebuild_action'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='action',
            new_name='goals_actio_goal_id_61b6db_idx',
            old_name='goals_acti_goal_id_43c5d6_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='goals_actio_goal_id_ddb3f1_idx',
            old_name='goals_acti_goal_id_cd3ede_idx',
        ),
        migrations.AddField(
            model_name='goal',
            name='default_reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='默认奖励金额'),
        ),
        migrations.AddField(
            model_name='goal',
            name='enable_reward',
            field=models.BooleanField(default=False, verbose_name='是否启用里程碑奖励'),
        ),
        migrations.AddField(
            model_name='goal',
            name='total_reward_issued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='本目标已发放奖励总额'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='里程碑奖励金额'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reward_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='奖励发放时间'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reward_synced',
            field=models.BooleanField(default=False, verbose_name='奖励是否已同步'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='reward_transaction_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='关联的奖励流水ID'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('planning', '计划中'), ('in-progress', '进行中'), ('paused', '已暂停'), ('completed', '已完成'), ('abandoned', '已放弃'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态'),
        ),
    ]
