# Generated by Django 6.0.4 on 2026-05-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_rename_goals_acti_goal_id_43c5d6_idx_goals_actio_goal_id_61b6db_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='completion_log',
            field=models.JSONField(blank=True, default=dict, verbose_name='打卡记录'),
        ),
        migrations.AddField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
