# Generated by Django 6.0.4 on 2026-06-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_action_completion_log_action_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('title', models.CharField(max_length=200, verbose_name='事项名称')),
                ('category', models.CharField(choices=[('work', '工作'), ('writing', '写作'), ('social', '社交'), ('study', '学习'), ('health', '健康'), ('life', '生活'), ('other', '其他')], default='other', max_length=50, verbose_name='类别')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('quality', models.CharField(choices=[('good', '良品'), ('defective', '不良品'), ('waste', '废品')], max_length=20, verbose_name='质量判定')),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1=轻车熟路, 5=完全未知', verbose_name='难度')),
                ('fail_reason', models.TextField(blank=True, verbose_name='失败原因（不良品/废品时填写）')),
                ('fail_type', models.CharField(blank=True, choices=[('cognitive', '认知盲区'), ('ability', '能力不足'), ('external', '外部因素'), ('luck', '运气'), ('careless', '粗心'), ('other', '其他')], max_length=50, verbose_name='失败类型')),
                ('lesson_learned', models.TextField(blank=True, verbose_name='经验教训')),
                ('occurred_at', models.DateField(blank=True, null=True, verbose_name='发生日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产出记录',
                'verbose_name_plural': '产出记录',
                'db_table': 'goals_output_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='goals_outpu_user_id_bc4881_idx'), models.Index(fields=['quality'], name='goals_outpu_quality_7aed5e_idx'), models.Index(fields=['category'], name='goals_outpu_categor_423939_idx')],
            },
        ),
    ]
