# Generated by Django 6.0.4 on 2026-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_outputrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_date',
            field=models.DateField(blank=True, null=True, verbose_name='发生日期'),
        ),
    ]
