# Generated by Django 6.0.4 on 2026-06-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_action_action_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='详细描述'),
        ),
    ]
