# Generated by Django 6.0.4 on 2026-06-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_milestone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='self_review',
            field=models.TextField(blank=True, default='', verbose_name='自我批阅'),
        ),
    ]
