# Generated by Django 6.0.4 on 2026-07-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_milestone_self_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='parent_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_goals', to='goals.goal', verbose_name='父目标'),
        ),
    ]
