# Generated by Django 6.0.4 on 2026-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_goal_parent_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='life_dimension',
            field=models.CharField(blank=True, choices=[('health', '🏃 健康'), ('wealth', '💰 财富'), ('relation', '👥 关系'), ('learning', '📚 学习'), ('career', '💼 事业'), ('leisure', '🌿 休闲'), ('other', '✨ 其他')], default='', max_length=20, verbose_name='人生维度'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='difficulty_met',
            field=models.TextField(blank=True, default='', verbose_name='遇到的困难'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='next_action',
            field=models.TextField(blank=True, default='', verbose_name='下一步行动'),
        ),
    ]
