# Generated by Django 6.0.4 on 2026-07-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_alter_goal_life_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_completion_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='目标完成奖励金'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='default_reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='每项里程碑奖励'),
        ),
    ]
