# Generated by Django 6.0.4 on 2026-07-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_add_goal_completion_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='life_dimension',
            field=models.CharField(choices=[('身体健康', '🏃 身体健康'), ('财富积累', '💰 财富积累'), ('学习成长', '📚 学习成长'), ('事业发展', '💼 事业发展'), ('休闲放松', '🌿 休闲放松'), ('系统建设', '🧰 系统建设'), ('创作输出', '🎨 创作输出'), ('生活空间', '🏠 生活空间'), ('其他事项', '✨ 其他事项')], max_length=20, verbose_name='人生维度'),
        ),
    ]
