# Generated by Django 6.0.4 on 2026-08-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_make_life_dimension_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('year', '年度目标'), ('quarter', '季度目标'), ('month', '月度目标'), ('long-term', '长期目标'), ('project', '项目目标')], max_length=50, verbose_name='目标类型'),
        ),
    ]
