# Generated by Django 6.0.4 on 2026-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID（预留）')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('category', models.CharField(choices=[('吃', '🍽️ 吃'), ('穿', '👔 穿'), ('用', '🧴 用'), ('店', '🏪 好店'), ('地方', '📍 好地方'), ('方法', '💡 好方法')], max_length=20, verbose_name='类别')),
                ('scene', models.CharField(blank=True, default='', max_length=200, verbose_name='什么场景遇到的')),
                ('why_good', models.TextField(verbose_name='为什么好')),
                ('still_available', models.BooleanField(default=True, verbose_name='还能找到吗')),
                ('where_to_find', models.CharField(blank=True, default='', max_length=200, verbose_name='在哪能找到')),
                ('tags', models.CharField(blank=True, default='', max_length=200, verbose_name='标签')),
                ('rating', models.IntegerField(default=5, verbose_name='评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '好东西',
                'verbose_name_plural': '好东西',
                'db_table': 'treasure_good_thing',
                'ordering': ['-created_at'],
            },
        ),
    ]
