# Generated by Django 6.0.4 on 2026-06-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodthing',
            options={'ordering': ['-created_at'], 'verbose_name': '双面档案', 'verbose_name_plural': '双面档案'},
        ),
        migrations.AddField(
            model_name='goodthing',
            name='avoid_reason',
            field=models.TextField(blank=True, default='', verbose_name='踩坑原因'),
        ),
        migrations.AddField(
            model_name='goodthing',
            name='consequence',
            field=models.TextField(blank=True, default='', verbose_name='实际后果'),
        ),
        migrations.AddField(
            model_name='goodthing',
            name='record_type',
            field=models.CharField(choices=[('好', '👍 好物'), ('歹', '👎 歹物')], default='好', max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='goodthing',
            name='why_good',
            field=models.TextField(blank=True, default='', verbose_name='为什么好'),
        ),
    ]
