# Generated by Django 6.0.4 on 2026-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='美食名称')),
                ('dish_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='具体菜名')),
                ('category', models.CharField(blank=True, choices=[('chinese', '中餐'), ('western', '西餐'), ('japanese', '日料'), ('dessert', '甜品'), ('snack', '小吃'), ('drink', '饮品'), ('other', '其他')], max_length=50, null=True, verbose_name='分类')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='具体位置')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('taste_level', models.CharField(choices=[('good', '好吃'), ('very_good', '特别好吃'), ('want_again', '还想吃'), ('must_eat_again', '一定要再吃')], default='good', max_length=20, verbose_name='美味等级')),
                ('eat_date', models.DateField(verbose_name='品尝日期')),
                ('eat_time', models.CharField(blank=True, choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '小吃')], max_length=20, null=True, verbose_name='时段')),
                ('companions', models.CharField(blank=True, max_length=200, null=True, verbose_name='同行伙伴')),
                ('occasion', models.CharField(blank=True, choices=[('date', '约会'), ('gathering', '聚餐'), ('solo', '独享'), ('travel', '旅游'), ('work', '工作餐')], max_length=100, null=True, verbose_name='场景')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='图片列表')),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='封面图')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='评分（1-5）')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='点评')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='标签')),
                ('want_visit_again', models.BooleanField(default=True, verbose_name='是否还想再去')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '美食记录',
                'verbose_name_plural': '美食记录',
                'db_table': 'food_record',
                'ordering': ['-eat_date', '-id'],
                'indexes': [models.Index(fields=['user_id'], name='food_record_user_id_3f6928_idx'), models.Index(fields=['province', 'city'], name='food_record_provinc_0ee76c_idx'), models.Index(fields=['taste_level'], name='food_record_taste_l_d32ece_idx'), models.Index(fields=['eat_date'], name='food_record_eat_dat_9ae558_idx'), models.Index(fields=['category'], name='food_record_categor_30ed5c_idx')],
            },
        ),
    ]
