# Generated by Django 6.0.4 on 2026-05-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE `hobby_dance_list` (
                  `id` bigint NOT NULL AUTO_INCREMENT,
                  `study_time` date DEFAULT NULL COMMENT '学习日期',
                  `score` int DEFAULT NULL COMMENT '自我评分（1-10）',
                  `teacher_name` varchar(20) DEFAULT NULL COMMENT '授课老师',
                  `dance_type` varchar(12) NOT NULL DEFAULT 'jazz' COMMENT '舞蹈类型：jazz, hiphop, 古典, 身体开发, MV, 形体软开',
                  `difficulty` varchar(10) NOT NULL DEFAULT '入门' COMMENT '难度等级：入门, 入门小班, 二星, 进阶',
                  `weekinfo` varchar(10) DEFAULT NULL COMMENT '周几（周一~周日）',
                  `remark` varchar(100) DEFAULT NULL COMMENT '备注',
                  `file_path` varchar(100) DEFAULT NULL COMMENT '录屏文件地址',
                  `year` int DEFAULT NULL COMMENT '年份',
                  `month` int DEFAULT NULL COMMENT '月份',
                  `quarter` int DEFAULT NULL COMMENT '季度',
                  `duration_minutes` int DEFAULT 60 COMMENT '课程时长（分钟）',
                  `energy_level` int DEFAULT NULL COMMENT '体能消耗（1-5）',
                  `improvement_note` varchar(200) DEFAULT NULL COMMENT '进步/待改进点',
                  PRIMARY KEY (`id`),
                  KEY `idx_study_time` (`study_time`),
                  KEY `idx_dance_type` (`dance_type`),
                  KEY `idx_teacher` (`teacher_name`),
                  KEY `idx_difficulty` (`difficulty`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3
            """,
            reverse_sql="DROP TABLE IF EXISTS `hobby_dance_list`",
            state_operations=[
                migrations.CreateModel(
                    name='DanceRecord',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('study_time', models.DateField(verbose_name='学习日期')),
                        ('score', models.IntegerField(verbose_name='自我评分')),
                        ('teacher_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='授课老师')),
                        ('dance_type', models.CharField(choices=[('jazz', 'Jazz'), ('hiphop', 'Hiphop'), ('古典', '古典'), ('身体开发', '身体开发'), ('MV', 'MV'), ('形体软开', '形体软开')], default='jazz', max_length=12, verbose_name='舞蹈类型')),
                        ('difficulty', models.CharField(choices=[('入门', '入门'), ('入门小班', '入门小班'), ('二星', '二星'), ('进阶', '进阶')], default='入门', max_length=10, verbose_name='难度等级')),
                        ('weekinfo', models.CharField(blank=True, max_length=10, null=True, verbose_name='周几')),
                        ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                        ('file_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='录屏文件地址')),
                        ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                        ('month', models.IntegerField(blank=True, null=True, verbose_name='月份')),
                        ('quarter', models.IntegerField(blank=True, null=True, verbose_name='季度')),
                        ('duration_minutes', models.IntegerField(default=60, verbose_name='课程时长（分钟）')),
                        ('energy_level', models.IntegerField(blank=True, null=True, verbose_name='体能消耗（1-5）')),
                        ('improvement_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='进步/待改进点')),
                    ],
                    options={
                        'verbose_name': '舞蹈记录',
                        'verbose_name_plural': '舞蹈记录',
                        'db_table': 'hobby_dance_list',
                        'ordering': ['-study_time'],
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
