# Generated by Django 6.0.4 on 2026-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('quarter', models.IntegerField(verbose_name='季度（1-4）')),
                ('question_key', models.CharField(max_length=100, verbose_name='问题标识')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('question_category', models.CharField(default='general', max_length=50, verbose_name='问题分类')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='用户回答')),
                ('related_module', models.CharField(blank=True, default='', max_length=30, verbose_name='关联模块')),
                ('action_taken', models.BooleanField(default=False, verbose_name='是否已采取行动')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '季度问答',
                'verbose_name_plural': '季度问答',
                'db_table': 'summary_quarterly_answer',
                'ordering': ['-year', '-quarter', 'created_at'],
                'unique_together': {('year', 'quarter', 'question_key')},
            },
        ),
    ]
