# Generated by Django 6.0.4 on 2026-05-05 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE temporal_time_atracker_tasks_list
                ADD COLUMN day int DEFAULT NULL COMMENT '日期' AFTER `mon`,
                ADD COLUMN week int DEFAULT NULL COMMENT '周数' AFTER `day`,
                ADD COLUMN quarter int DEFAULT NULL COMMENT '季度' AFTER `week`,
                ADD COLUMN category_level1 varchar(50) DEFAULT NULL COMMENT '一级分类' AFTER `quarter`,
                ADD COLUMN category_level2 varchar(50) DEFAULT NULL COMMENT '二级分类' AFTER `category_level1`,
                ADD COLUMN category_color varchar(20) DEFAULT NULL COMMENT '分类颜色' AFTER `category_level2`,
                ADD COLUMN import_batch varchar(50) DEFAULT NULL COMMENT '导入批次号' AFTER `category_color`,
                ADD COLUMN updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' AFTER `import_batch`,
                ADD INDEX idx_start_time (`start_time`),
                ADD INDEX idx_task_name (`task_name`),
                ADD INDEX idx_category (`category_level1`, `category_level2`),
                ADD INDEX idx_year_month (`year`, `mon`)
            """,
            reverse_sql="""
                ALTER TABLE temporal_time_atracker_tasks_list
                DROP INDEX idx_year_month,
                DROP INDEX idx_category,
                DROP INDEX idx_task_name,
                DROP INDEX idx_start_time,
                DROP COLUMN updated_at,
                DROP COLUMN import_batch,
                DROP COLUMN category_color,
                DROP COLUMN category_level2,
                DROP COLUMN category_level1,
                DROP COLUMN quarter,
                DROP COLUMN week,
                DROP COLUMN day
            """,
            state_operations=[
                migrations.CreateModel(
                    name='OneDayPage',
                    fields=[
                        ('oid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                        ('years', models.CharField(blank=True, max_length=25, null=True, verbose_name='年度')),
                        ('oneday', models.IntegerField(blank=True, null=True, verbose_name='oneday字数')),
                        ('page', models.IntegerField(blank=True, null=True, verbose_name='文章字数')),
                        ('total', models.IntegerField(blank=True, null=True, verbose_name='总字数')),
                        ('title', models.CharField(max_length=255, verbose_name='主题')),
                        ('begin_date', models.DateField(db_column='beginDate', default=django.utils.timezone.localdate, verbose_name='创建日期')),
                        ('otype', models.CharField(choices=[('MIGU', '迷谷知松'), ('HAPPY', '有点开心'), ('SAD', '有点闹心'), ('DIGITAL', '数字转型'), ('SUMMARY', '复盘总结'), ('ONEDAY', '普通一日'), ('IDEA', '有点想法'), ('ACHIEVE', '有点成就')], default='ONEDAY', max_length=50, verbose_name='内容类型')),
                        ('update_date', models.DateField(db_column='updateDate', default=django.utils.timezone.localdate, verbose_name='更新日期')),
                        ('flag', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                        ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                        ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='预留用户ID')),
                    ],
                    options={
                        'verbose_name': '每日记录',
                        'verbose_name_plural': '每日记录',
                        'db_table': 'temporal_oneday_page_list',
                        'ordering': ['-begin_date'],
                        'managed': False,
                    },
                ),
                migrations.CreateModel(
                    name='TemporalTask',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('task_name', models.CharField(max_length=255, verbose_name='任务名称')),
                        ('task_description', models.TextField(blank=True, null=True, verbose_name='任务说明')),
                        ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                        ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                        ('duration', models.TimeField(blank=True, null=True, verbose_name='持续时间')),
                        ('duration_hours', models.FloatField(blank=True, null=True, verbose_name='持续小时数')),
                        ('notes', models.TextField(blank=True, null=True, verbose_name='附注')),
                        ('tags', models.TextField(blank=True, null=True, verbose_name='标签')),
                        ('task_type', models.CharField(default='其他', max_length=100, verbose_name='任务类型')),
                        ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                        ('mon', models.CharField(blank=True, max_length=10, null=True, verbose_name='月份')),
                        ('day', models.IntegerField(blank=True, null=True, verbose_name='日期')),
                        ('week', models.IntegerField(blank=True, null=True, verbose_name='周数')),
                        ('quarter', models.IntegerField(blank=True, null=True, verbose_name='季度')),
                        ('category_level1', models.CharField(blank=True, choices=[('生产与创造', '生产与创造'), ('维护与秩序', '维护与秩序'), ('滋养与成长', '滋养与成长'), ('连接与记录', '连接与记录')], max_length=50, null=True, verbose_name='一级分类')),
                        ('category_level2', models.CharField(blank=True, max_length=50, null=True, verbose_name='二级分类')),
                        ('category_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='分类颜色')),
                        ('import_batch', models.CharField(blank=True, max_length=50, null=True, verbose_name='导入批次号')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                    ],
                    options={
                        'verbose_name': '任务时间记录',
                        'verbose_name_plural': '任务时间记录',
                        'db_table': 'temporal_time_atracker_tasks_list',
                        'ordering': ['-start_time'],
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
