# Generated by Django 6.0.4 on 2026-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimeCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('week', models.IntegerField(verbose_name='周次')),
                ('total_hours', models.FloatField(default=0, verbose_name='本周总小时')),
                ('task_count', models.IntegerField(default=0, verbose_name='任务数')),
                ('avg_hours_per_day', models.FloatField(default=0, verbose_name='日均小时')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'temporal_weekly_time_cache',
                'ordering': ['year', 'week'],
                'indexes': [models.Index(fields=['year'], name='temporal_we_year_b8d9d1_idx')],
                'unique_together': {('year', 'week')},
            },
        ),
    ]
