# Generated by Django 6.0.4 on 2026-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WealthCurrentScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now=True, verbose_name='推演时间点')),
                ('current_age', models.IntegerField(verbose_name='当前年龄(18-78)')),
                ('current_week', models.IntegerField(verbose_name='当前周数(1-52)')),
                ('current_cash', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='当前现金(元)')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每日预算(元/天)')),
                ('support_weeks', models.IntegerField(default=0, verbose_name='可支撑周数')),
                ('end_age', models.IntegerField(blank=True, null=True, verbose_name='资金耗尽时的年龄')),
                ('end_week', models.IntegerField(blank=True, null=True, verbose_name='资金耗尽时的周数')),
            ],
            options={
                'verbose_name': '当前推演状态',
                'verbose_name_plural': '当前推演状态',
                'db_table': 'wealth_current_scenario',
            },
        ),
        migrations.CreateModel(
            name='WealthScenarioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True, verbose_name='推演时间点')),
                ('current_age', models.IntegerField(verbose_name='当前年龄')),
                ('current_week', models.IntegerField(verbose_name='当前周数')),
                ('current_cash', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='当前现金')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每日预算')),
                ('support_weeks', models.IntegerField(default=0, verbose_name='可支撑周数')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '推演历史',
                'verbose_name_plural': '推演历史',
                'db_table': 'wealth_scenario_history',
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='WealthLifeWeekCalendar',
            fields=[
                ('global_week_index', models.IntegerField(primary_key=True, serialize=False, verbose_name='全局周索引(0-3171)')),
                ('age_year', models.IntegerField(verbose_name='年龄(18-78)')),
                ('week_number', models.IntegerField(verbose_name='周数(1-52)')),
                ('week_start_date', models.DateField(verbose_name='该周起始日期')),
                ('week_end_date', models.DateField(verbose_name='该周结束日期')),
                ('is_lived', models.BooleanField(default=False, verbose_name='是否已度过')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '人生周历',
                'verbose_name_plural': '人生周历',
                'db_table': 'wealth_life_week_calendar',
                'indexes': [models.Index(fields=['user_id', 'global_week_index'], name='wealth_life_user_id_27782a_idx')],
            },
        ),
    ]
