# Generated by Django 6.0.4 on 2026-08-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('wealth', '0001_initial'), ('wealth', '0002_wealthbalancelist_wealthcashflow'), ('wealth', '0003_wealthregularlist_and_more'), ('wealth', '0004_alter_wealthcurrentscenario_daily_interest_rate_and_more'), ('wealth', '0005_fundpool_monthlybudget_poolallocation'), ('wealth', '0006_remove_poolallocation_monthly_budget_and_more'), ('wealth', '0007_remove_fundtransaction_pool_delete_fundpool_and_more'), ('wealth', '0008_allocationcategory_allocationplan_commitment_and_more'), ('wealth', '0009_fundschedule_remove_allocationitem_category_and_more')]


    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WealthBalanceList',
            fields=[
                ('yearmon', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='年月')),
                ('wageincome', models.FloatField(blank=True, db_column='wageIncome', null=True, verbose_name='工资收入')),
                ('otherincome', models.FloatField(blank=True, db_column='otherIncome', null=True, verbose_name='其他收入')),
                ('outmoney', models.FloatField(blank=True, null=True, verbose_name='支出')),
                ('mbalance', models.FloatField(blank=True, null=True, verbose_name='每月余额')),
                ('btime', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='流水余额')),
                ('accumulationfund', models.FloatField(blank=True, null=True, verbose_name='公积金')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='总存款')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='距离')),
                ('borrow', models.FloatField(blank=True, null=True, verbose_name='借贷')),
                ('lend', models.FloatField(blank=True, null=True, verbose_name='借出')),
                ('realnum', models.FloatField(blank=True, null=True, verbose_name='真正在手里的')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID预留')),
            ],
            options={
                'verbose_name': '月度收支复盘',
                'verbose_name_plural': '月度收支复盘',
                'db_table': 'wealth_balance_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WealthCashFlow',
            fields=[
                ('baid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('yearmon', models.CharField(blank=True, max_length=10, null=True, verbose_name='年月')),
                ('zplay', models.FloatField(blank=True, null=True, verbose_name='支付宝')),
                ('wechat', models.FloatField(blank=True, null=True, verbose_name='微信')),
                ('cash', models.FloatField(blank=True, null=True, verbose_name='现金')),
                ('jianbank', models.FloatField(blank=True, null=True, verbose_name='建行')),
                ('gongbank', models.FloatField(blank=True, null=True, verbose_name='工行')),
                ('zhongbank', models.FloatField(blank=True, null=True, verbose_name='中国银行')),
                ('nongbank', models.FloatField(blank=True, null=True, verbose_name='农村信用社')),
                ('accumulationfund', models.FloatField(blank=True, null=True, verbose_name='公积金')),
                ('lend', models.FloatField(blank=True, null=True, verbose_name='借出')),
                ('borrow', models.FloatField(blank=True, null=True, verbose_name='负债')),
                ('flow_total', models.FloatField(blank=True, null=True, verbose_name='总现金流')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='总额')),
                ('btime', models.DateField(blank=True, null=True, verbose_name='复盘时间')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('realnum', models.FloatField(blank=True, null=True, verbose_name='真正在手里的')),
            ],
            options={
                'verbose_name': '现金盘点',
                'verbose_name_plural': '现金盘点',
                'db_table': 'wealth_cash_flow',
                'ordering': ['-yearmon'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WealthRegularList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('begin_date', models.DateField(verbose_name='存入日期')),
                ('end_date', models.DateField(verbose_name='到期日期')),
                ('value', models.FloatField(verbose_name='存款金额')),
                ('flag', models.IntegerField(default=0, verbose_name='状态(0未到期/1已到期/2已取出)')),
                ('interest', models.FloatField(blank=True, null=True, verbose_name='利息')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('bankinfo', models.CharField(blank=True, max_length=20, null=True, verbose_name='银行')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='年利率(%)')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '定期存款',
                'verbose_name_plural': '定期存款',
                'db_table': 'wealth_regular_list',
                'ordering': ['-end_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('plan_name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='手里现金')),
                ('reserve_items', models.JSONField(default=list, help_text='[{name, amount, type: hard|soft, linked_expense_id}]', verbose_name='预留项目')),
                ('total_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预留合计')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='剩余可分配')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资金排程',
                'verbose_name_plural': '资金排程',
                'db_table': 'wealth_fund_schedule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WealthCurrentScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now=True, verbose_name='推演时间点')),
                ('current_age', models.IntegerField(verbose_name='当前年龄(18-78)')),
                ('current_week', models.IntegerField(verbose_name='当前周数(1-52)')),
                ('current_cash', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='当前现金(元)')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每日预算(元/天)')),
                ('daily_interest_rate', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='日利息率(小数)')),
                ('support_weeks', models.IntegerField(default=0, verbose_name='可支撑周数')),
                ('end_age', models.IntegerField(blank=True, null=True, verbose_name='资金耗尽时的年龄')),
                ('end_week', models.IntegerField(blank=True, null=True, verbose_name='资金耗尽时的周数')),
            ],
            options={
                'verbose_name': '当前推演状态',
                'verbose_name_plural': '当前推演状态',
                'db_table': 'wealth_current_scenario',
            },
        ),
        migrations.CreateModel(
            name='WealthScenarioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_time', models.DateTimeField(auto_now_add=True, verbose_name='推演时间点')),
                ('current_age', models.IntegerField(verbose_name='当前年龄')),
                ('current_week', models.IntegerField(verbose_name='当前周数')),
                ('current_cash', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='当前现金')),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每日预算')),
                ('daily_interest_rate', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='日利息率(小数)')),
                ('support_weeks', models.IntegerField(default=0, verbose_name='可支撑周数')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '推演历史',
                'verbose_name_plural': '推演历史',
                'db_table': 'wealth_scenario_history',
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='WealthLifeWeekCalendar',
            fields=[
                ('global_week_index', models.IntegerField(primary_key=True, serialize=False, verbose_name='全局周索引(0-3171)')),
                ('age_year', models.IntegerField(verbose_name='年龄(18-78)')),
                ('week_number', models.IntegerField(verbose_name='周数(1-52)')),
                ('week_start_date', models.DateField(verbose_name='该周起始日期')),
                ('week_end_date', models.DateField(verbose_name='该周结束日期')),
                ('is_lived', models.BooleanField(default=False, verbose_name='是否已度过')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '人生周历',
                'verbose_name_plural': '人生周历',
                'db_table': 'wealth_life_week_calendar',
                'indexes': [models.Index(fields=['user_id', 'global_week_index'], name='wealth_life_user_id_27782a_idx')],
            },
        ),
    ]
