# Generated by Django 6.0.4 on 2026-05-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WealthBalanceList',
            fields=[
                ('age', models.FloatField(verbose_name='年龄')),
                ('yearmon', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='年月')),
                ('wageincome', models.FloatField(blank=True, db_column='wageIncome', null=True, verbose_name='工资收入')),
                ('otherincome', models.FloatField(blank=True, db_column='otherIncome', null=True, verbose_name='其他收入')),
                ('outmoney', models.FloatField(blank=True, null=True, verbose_name='支出')),
                ('mbalance', models.FloatField(blank=True, null=True, verbose_name='每月余额')),
                ('btime', models.DateTimeField(blank=True, null=True, verbose_name='日期')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='流水余额')),
                ('accumulationfund', models.FloatField(blank=True, null=True, verbose_name='公积金')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='总存款')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='距离')),
                ('borrow', models.FloatField(blank=True, null=True, verbose_name='借贷')),
                ('lend', models.FloatField(blank=True, null=True, verbose_name='借出')),
                ('realnum', models.FloatField(blank=True, null=True, verbose_name='真正在手里的')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID预留')),
            ],
            options={
                'verbose_name': '月度收支复盘',
                'verbose_name_plural': '月度收支复盘',
                'db_table': 'wealth_balance_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WealthCashFlow',
            fields=[
                ('baid', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('yearmon', models.CharField(blank=True, max_length=10, null=True, verbose_name='年月')),
                ('zplay', models.FloatField(blank=True, null=True, verbose_name='支付宝')),
                ('wechat', models.FloatField(blank=True, null=True, verbose_name='微信')),
                ('cash', models.FloatField(blank=True, null=True, verbose_name='现金')),
                ('jianbank', models.FloatField(blank=True, null=True, verbose_name='建行')),
                ('gongbank', models.FloatField(blank=True, null=True, verbose_name='工行')),
                ('zhongbank', models.FloatField(blank=True, null=True, verbose_name='中国银行')),
                ('nongbank', models.FloatField(blank=True, null=True, verbose_name='农村信用社')),
                ('accumulationfund', models.FloatField(blank=True, null=True, verbose_name='公积金')),
                ('lend', models.FloatField(blank=True, null=True, verbose_name='借出')),
                ('borrow', models.FloatField(blank=True, null=True, verbose_name='负债')),
                ('flow_total', models.FloatField(blank=True, null=True, verbose_name='总现金流')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='总额')),
                ('btime', models.DateField(blank=True, null=True, verbose_name='复盘时间')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('realnum', models.FloatField(blank=True, null=True, verbose_name='真正在手里的')),
            ],
            options={
                'verbose_name': '现金盘点',
                'verbose_name_plural': '现金盘点',
                'db_table': 'wealth_cash_flow',
                'ordering': ['-yearmon'],
                'managed': False,
            },
        ),
    ]
