# Generated by Django 6.0.4 on 2026-07-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0002_wealthbalancelist_wealthcashflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WealthRegularList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('begin_date', models.DateField(verbose_name='存入日期')),
                ('end_date', models.DateField(verbose_name='到期日期')),
                ('value', models.FloatField(verbose_name='存款金额')),
                ('flag', models.IntegerField(default=0, verbose_name='状态(0未到期/1已到期/2已取出)')),
                ('interest', models.FloatField(blank=True, null=True, verbose_name='利息')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('bankinfo', models.CharField(blank=True, max_length=20, null=True, verbose_name='银行')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='年利率(%)')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '定期存款',
                'verbose_name_plural': '定期存款',
                'db_table': 'wealth_regular_list',
                'ordering': ['-end_date'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='wealthcurrentscenario',
            name='daily_interest_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='日利息率(小数)'),
        ),
        migrations.AddField(
            model_name='wealthscenariohistory',
            name='daily_interest_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8, verbose_name='日利息率(小数)'),
        ),
    ]
