# Generated by Django 6.0.4 on 2026-07-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0003_wealthregularlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wealthcurrentscenario',
            name='daily_interest_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='日利息率(小数)'),
        ),
        migrations.AlterField(
            model_name='wealthscenariohistory',
            name='daily_interest_rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='日利息率(小数)'),
        ),
    ]
