# Generated by Django 6.0.4 on 2026-08-11 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0004_alter_wealthcurrentscenario_daily_interest_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='池名称')),
                ('icon', models.CharField(default='💰', max_length=10, verbose_name='图标')),
                ('color', models.CharField(default='#409EFF', max_length=10, verbose_name='颜色')),
                ('pool_type', models.CharField(choices=[('fixed', '固定金额'), ('ratio', '收入比例'), ('reservoir', '蓄水池')], default='ratio', max_length=10, verbose_name='分配类型')),
                ('default_value', models.DecimalField(decimal_places=2, default=0, help_text='ratio: 百分比(0-100), fixed: 固定金额, reservoir: 目标金额', max_digits=10, verbose_name='默认值')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('intent', models.CharField(blank=True, help_text='这个池子支持我人生的哪个维度？', max_length=200, verbose_name='人生意图')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wealth_fund_pool',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, unique=True, verbose_name='年月')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当月总收入')),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总分配金额')),
                ('initial_fund', models.DecimalField(decimal_places=2, default=0, help_text='一次性注入的总池资金', max_digits=12, verbose_name='初始注入资金')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('closed', '已结账')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wealth_monthly_budget',
                'ordering': ['-year_month'],
            },
        ),
        migrations.CreateModel(
            name='PoolAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='本次分配金额')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已花费')),
                ('rollover_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='上月结转')),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='剩余可用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='wealth.monthlybudget')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wealth.fundpool')),
            ],
            options={
                'db_table': 'wealth_pool_allocation',
                'unique_together': {('monthly_budget', 'pool')},
            },
        ),
    ]
