# Generated by Django 6.0.4 on 2026-08-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0005_fundpool_monthlybudget_poolallocation'),
    ]

    operations = [
        # 资金分配 v2.0：废弃月度预算模式，改为持续资金池 + 流水
        migrations.AddField(
            model_name='fundpool',
            name='linked_categories',
            field=models.JSONField(blank=True, default=list, help_text='如 ["餐饮", "交通"]，匹配账单分类', verbose_name='关联分类'),
        ),
        migrations.AlterField(
            model_name='fundpool',
            name='default_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='fixed: 每月建议金额 | ratio: 建议比例(%) | reservoir: 目标金额', max_digits=10, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='fundpool',
            name='priority',
            field=models.IntegerField(default=0, help_text='数字越小越优先', verbose_name='优先级'),
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('inject', '💎 注入资金'), ('allocate', '💰 分配资金'), ('spend', '💸 消费扣减'), ('adjust', '✏️ 手动调整'), ('refund', '↩️ 退款返还')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数=增加余额，负数=减少余额', max_digits=12, verbose_name='金额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='操作后余额')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('bill_id', models.IntegerField(blank=True, help_text='如果是消费扣减', null=True, verbose_name='关联账单ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wealth.fundpool')),
            ],
            options={
                'db_table': 'wealth_fund_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MonthlyBudget',
        ),
        migrations.DeleteModel(
            name='PoolAllocation',
        ),
    ]
