# Generated by Django 6.0.4 on 2026-08-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0006_remove_poolallocation_monthly_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundtransaction',
            name='pool',
        ),
        migrations.DeleteModel(
            name='FundPool',
        ),
        migrations.DeleteModel(
            name='FundTransaction',
        ),
    ]
