# Generated by Django 6.0.4 on 2026-08-14 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0007_remove_fundtransaction_pool_delete_fundpool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别名称')),
                ('icon', models.CharField(default='💰', max_length=10, verbose_name='图标')),
                ('color', models.CharField(default='#409EFF', max_length=10, verbose_name='颜色')),
                ('priority', models.IntegerField(default=0, help_text='数字越小越优先预留', verbose_name='优先级')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='默认金额')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分配类别',
                'verbose_name_plural': '分配类别',
                'db_table': 'wealth_allocation_category',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AllocationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, verbose_name='年月')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='手头现金')),
                ('commitments_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='硬性承诺合计')),
                ('allocated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预留分配合计')),
                ('free_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='自由支配')),
                ('status', models.CharField(default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '分配计划',
                'verbose_name_plural': '分配计划',
                'db_table': 'wealth_allocation_plan',
                'ordering': ['-year_month'],
                'unique_together': {('year_month',)},
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('status', models.CharField(choices=[('pending', '待付'), ('urgent', '紧急'), ('done', '已付')], default='pending', max_length=10, verbose_name='状态')),
                ('source', models.CharField(choices=[('bill', '账单'), ('inbox', '收件箱'), ('manual', '手动录入')], default='manual', max_length=20, verbose_name='来源')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='wealth.allocationplan')),
            ],
            options={
                'verbose_name': '硬性承诺',
                'verbose_name_plural': '硬性承诺',
                'db_table': 'wealth_commitment',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='决策内容')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='类别')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wealth.allocationplan')),
            ],
            options={
                'verbose_name': '自由决策记录',
                'verbose_name_plural': '自由决策记录',
                'db_table': 'wealth_decision_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划预留金额')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已花费')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='剩余')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wealth.allocationcategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wealth.allocationplan')),
            ],
            options={
                'verbose_name': '分配明细项',
                'verbose_name_plural': '分配明细项',
                'db_table': 'wealth_allocation_item',
                'unique_together': {('plan', 'category')},
            },
        ),
    ]
