# Generated by Django 6.0.4 on 2026-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0008_allocationcategory_allocationplan_commitment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('plan_name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='手里现金')),
                ('reserve_items', models.JSONField(default=list, help_text='[{name, amount, type: hard|soft, linked_expense_id}]', verbose_name='预留项目')),
                ('total_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预留合计')),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='剩余可分配')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '资金排程',
                'verbose_name_plural': '资金排程',
                'db_table': 'wealth_fund_schedule',
                'ordering': ['-created_at'],
            },
        ),
        # 先删组合唯一索引再删列：MySQL 在删除参与唯一索引的列时会用剩余列重建索引，
        # 同一 plan 有多条 item 时必然撞唯一键（Duplicate entry）。
        migrations.AlterUniqueTogether(
            name='allocationitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='allocationitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='allocationitem',
            name='plan',
        ),
        migrations.AlterUniqueTogether(
            name='allocationplan',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='decisionlog',
            name='plan',
        ),
        migrations.DeleteModel(
            name='AllocationCategory',
        ),
        migrations.DeleteModel(
            name='AllocationItem',
        ),
        migrations.DeleteModel(
            name='Commitment',
        ),
        migrations.DeleteModel(
            name='AllocationPlan',
        ),
        migrations.DeleteModel(
            name='DecisionLog',
        ),
    ]
