# Generated by Django 6.0.4 on 2026-08-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_squashed_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundschedule',
            name='reserve_items',
            field=models.JSONField(default=list, help_text='[{name, amount, type: hard|soft, linked_expense_id}]', verbose_name='预留项目（已废弃，见 wealth_fund_schedule_item）'),
        ),
        migrations.CreateModel(
            name='FundScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='预留项名称')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额')),
                ('item_type', models.CharField(default='hard', max_length=10, verbose_name='类型')),
                ('linked_expense_id', models.IntegerField(blank=True, null=True, verbose_name='关联支出ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wealth.fundschedule')),
            ],
            options={
                'verbose_name': '预留项',
                'verbose_name_plural': '预留项',
                'db_table': 'wealth_fund_schedule_item',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['schedule'], name='wealth_fund_schedul_df0f17_idx')],
            },
        ),
    ]
