# Generated by Django 6.0.4 on 2026-08-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0010_alter_fundschedule_reserve_items_fundscheduleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundschedule',
            name='reserve_items',
        ),
    ]
