# Generated by Django 6.0.4 on 2026-08-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0012_balancelist_rename_camelcase_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='WealthBillList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=10, verbose_name='收支类型')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True, verbose_name='子分类')),
                ('project', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目')),
                ('account', models.CharField(blank=True, max_length=50, null=True, verbose_name='账户')),
                ('account_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='币种')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('member', models.CharField(blank=True, max_length=50, null=True, verbose_name='成员')),
                ('merchant', models.CharField(blank=True, max_length=100, null=True, verbose_name='商户')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('related_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='关联ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '账单明细',
                'verbose_name_plural': '账单明细',
                'db_table': 'wealth_bill_list',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
    ]
