# Generated by Django 6.0.4 on 2026-05-11 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='条目ID')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('description', models.TextField(blank=True, null=True, verbose_name='详细描述')),
                ('category', models.CharField(choices=[('todo', '待办'), ('idea', '想法'), ('pain', '痛点'), ('reminder', '提醒'), ('other', '其他')], default='other', max_length=50, verbose_name='类别')),
                ('tags', models.CharField(blank=True, max_length=500, null=True, verbose_name='标签（逗号分隔）')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('done', '已完成'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态')),
                ('source', models.CharField(choices=[('manual', '手动'), ('import', '导入'), ('voice', '语音'), ('auto', '自动')], default='manual', max_length=50, verbose_name='来源')),
                ('target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标模块类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标模块ID')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收件箱条目',
                'verbose_name_plural': '收件箱条目',
                'db_table': 'inbox_item',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='inbox_item_user_id_2b130b_idx'), models.Index(fields=['status'], name='inbox_item_status_9d048e_idx'), models.Index(fields=['category'], name='inbox_item_categor_d53631_idx'), models.Index(fields=['created_at'], name='inbox_item_created_b911f7_idx'), models.Index(fields=['due_date'], name='inbox_item_due_dat_545218_idx'), models.Index(fields=['target_type', 'target_id'], name='inbox_item_target__2467b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboxProcessLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('action', models.CharField(choices=[('convert_to_goal', '转为目标'), ('convert_to_sugar', '转为能量'), ('convert_to_relationship', '转为互动'), ('complete', '完成'), ('archive', '归档')], max_length=50, verbose_name='操作')),
                ('target_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标模块类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标模块ID')),
                ('notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='inbox.inboxitem', verbose_name='关联条目')),
            ],
            options={
                'verbose_name': '处理日志',
                'verbose_name_plural': '处理日志',
                'db_table': 'inbox_process_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inbox'], name='inbox_proce_inbox_i_fa868c_idx'), models.Index(fields=['user_id'], name='inbox_proce_user_id_828ffa_idx')],
            },
        ),
    ]
