# Generated by Django 6.0.4 on 2026-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='completion_note',
            field=models.TextField(blank=True, default='', verbose_name='完成备注'),
        ),
        migrations.AlterField(
            model_name='inboxprocesslog',
            name='action',
            field=models.CharField(choices=[('convert_to_goal', '转为目标'), ('convert_to_sugar', '转为能量'), ('complete', '完成'), ('archive', '归档')], max_length=50, verbose_name='操作'),
        ),
    ]
