# Generated by Django 6.0.4 on 2026-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inboxitem_completion_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='hesitate_reason',
            field=models.TextField(blank=True, default='', verbose_name='犹豫原因'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='category',
            field=models.CharField(choices=[('todo', '待办'), ('idea', '想法'), ('pain', '痛点'), ('reminder', '提醒'), ('work', '工作'), ('other', '其他')], default='other', max_length=50, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('hesitating', '犹豫中'), ('processed', '已处理'), ('done', '已完成'), ('archived', '已归档')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='inboxprocesslog',
            name='action',
            field=models.CharField(choices=[('convert_to_goal', '转为目标'), ('convert_to_milestone', '转为里程碑'), ('convert_to_sugar', '转为能量'), ('complete', '完成'), ('archive', '归档')], max_length=50, verbose_name='操作'),
        ),
    ]
