# Generated by Django 6.0.4 on 2026-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_inboxitem_hesitate_reason_alter_inboxitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='category',
            field=models.CharField(default='other', max_length=50, verbose_name='类别'),
        ),
    ]
