# Generated by Django 6.0.4 on 2026-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_alter_inbox_category_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='abandon_reason',
            field=models.TextField(blank=True, default='', verbose_name='废弃原因'),
        ),
        migrations.AlterField(
            model_name='inboxitem',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('hesitating', '犹豫中'), ('processed', '已处理'), ('done', '已完成'), ('archived', '已归档'), ('abandoned', '已废弃')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
