# Generated by Django 6.0.4 on 2026-08-18 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='用户ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='计划出发日期')),
                ('status', models.CharField(choices=[('计划中', '计划中'), ('进行中', '进行中'), ('已完成', '已完成'), ('已取消', '已取消')], default='计划中', max_length=20, verbose_name='状态')),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估总费用')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '旅行计划',
                'db_table': 'travel_plan',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('food', '🍽️ 美食'), ('scenic', '📍 景点'), ('transport', '🚗 交通'), ('hotel', '🏠 住宿')], max_length=20, verbose_name='类型')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('estimate_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估费用')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.travelplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '旅行计划子项',
                'db_table': 'travel_plan_item',
                'ordering': ['item_type', 'sort_order'],
            },
        ),
    ]
