# Generated by Django 6.0.4 on 2026-05-08 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamsFileResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='文件名')),
                ('path', models.TextField(verbose_name='完整路径')),
                ('storage_location', models.CharField(blank=True, default='', max_length=200, verbose_name='存储位置')),
                ('file_category', models.CharField(blank=True, choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('code', '代码'), ('executable', '可执行文件'), ('other', '其他')], default='', max_length=50, verbose_name='文件分类')),
                ('file_size_mb', models.FloatField(default=0, verbose_name='文件大小(MB)')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('folder_depth', models.IntegerField(default=0, verbose_name='文件夹深度')),
                ('parent_folder', models.CharField(blank=True, default='', max_length=500, verbose_name='父文件夹')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='是否重复')),
                ('is_organized', models.BooleanField(default=False, verbose_name='是否已整理')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件资源',
                'verbose_name_plural': '文件资源',
                'db_table': 'dams_file_resource',
                'ordering': ['-updated_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DamsAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(verbose_name='访问时间')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='dams.damsfileresource', verbose_name='关联文件')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'db_table': 'dams_access_log',
                'ordering': ['-accessed_at'],
                'managed': True,
            },
        ),
    ]
